# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

indexSuccess:
  layout: homepage
  javascripts:
    - mailchimp_subscribe.js
    - /libs/jquery-colorbox/jquery.colorbox-min.js?v=1.5.14
  stylesheets:
    - dist/landing.css?v=3
    - /libs/jquery-colorbox/colorbox.css?v=1.5.14
