<?php

/**
 * BaseRoleFilter
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $decision_id
 * @property integer $role_id
 * @property Decision $Decision
 * @property Role $Role
 * 
 * @method integer    getDecisionId()  Returns the current record's "decision_id" value
 * @method integer    getRoleId()      Returns the current record's "role_id" value
 * @method Decision   getDecision()    Returns the current record's "Decision" value
 * @method Role       getRole()        Returns the current record's "Role" value
 * @method RoleFilter setDecisionId()  Sets the current record's "decision_id" value
 * @method RoleFilter setRoleId()      Sets the current record's "role_id" value
 * @method RoleFilter setDecision()    Sets the current record's "Decision" value
 * @method RoleFilter setRole()        Sets the current record's "Role" value
 * 
 * @package    dmp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRoleFilter extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('role_filter');
        $this->hasColumn('decision_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('role_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));


        $this->index('role_filter_decsion_idx', array(
             'fields' => 
             array(
              0 => 'role_id',
              1 => 'decision_id',
             ),
             'type' => 'unique',
             ));
        $this->option('symfony', array(
             'filter' => false,
             'form' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Decision', array(
             'local' => 'decision_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Role', array(
             'local' => 'role_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}