<?php

/**
 * BaseScripts
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property varchar $backend_top
 * @property varchar $backend_bottom
 * @property varchar $frontend_top
 * @property varchar $frontend_bottom
 * 
 * @method varchar getBackendTop()      Returns the current record's "backend_top" value
 * @method varchar getBackendBottom()   Returns the current record's "backend_bottom" value
 * @method varchar getFrontendTop()     Returns the current record's "frontend_top" value
 * @method varchar getFrontendBottom()  Returns the current record's "frontend_bottom" value
 * @method Scripts setBackendTop()      Sets the current record's "backend_top" value
 * @method Scripts setBackendBottom()   Sets the current record's "backend_bottom" value
 * @method Scripts setFrontendTop()     Sets the current record's "frontend_top" value
 * @method Scripts setFrontendBottom()  Sets the current record's "frontend_bottom" value
 * 
 * @package    dmp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseScripts extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('scripts');
        $this->hasColumn('backend_top', 'varchar', 2000, array(
             'type' => 'varchar',
             'length' => 2000,
             ));
        $this->hasColumn('backend_bottom', 'varchar', 2000, array(
             'type' => 'varchar',
             'length' => 2000,
             ));
        $this->hasColumn('frontend_top', 'varchar', 2000, array(
             'type' => 'varchar',
             'length' => 2000,
             ));
        $this->hasColumn('frontend_bottom', 'varchar', 2000, array(
             'type' => 'varchar',
             'length' => 2000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}