<?php

/**
 * BaseRoleTemplate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $template_id
 * @property TypeTemplate $Template
 * 
 * @method string       getName()        Returns the current record's "name" value
 * @method integer      getTemplateId()  Returns the current record's "template_id" value
 * @method TypeTemplate getTemplate()    Returns the current record's "Template" value
 * @method RoleTemplate setName()        Sets the current record's "name" value
 * @method RoleTemplate setTemplateId()  Sets the current record's "template_id" value
 * @method RoleTemplate setTemplate()    Sets the current record's "Template" value
 * 
 * @package    dmp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRoleTemplate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('role_template');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('template_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('symfony', array(
             'filter' => false,
             'form' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TypeTemplate as Template', array(
             'local' => 'template_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}