<?php

/**
 * BasePromoCode
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $code
 * @property enum $account_type
 * 
 * @method string    getCode()         Returns the current record's "code" value
 * @method enum      getAccountType()  Returns the current record's "account_type" value
 * @method PromoCode setCode()         Sets the current record's "code" value
 * @method PromoCode setAccountType()  Sets the current record's "account_type" value
 * 
 * @package    dmp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePromoCode extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('promo_code');
        $this->hasColumn('code', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('account_type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Trial',
              1 => 'Light',
              2 => 'Basic',
              3 => 'Pro',
              4 => 'Enterprise',
             ),
             'default' => 'Trial',
             ));

        $this->option('symfony', array(
             'filter' => true,
             'form' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}