<?php

/**
 * BaseDecisionType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property Doctrine_Collection $Users
 * @property Doctrine_Collection $AlternativeType
 * @property Doctrine_Collection $TypeTemplate
 * @property Doctrine_Collection $UserDecisionType
 * @property Doctrine_Collection $Decision
 * 
 * @method string              getName()             Returns the current record's "name" value
 * @method string              getDescription()      Returns the current record's "description" value
 * @method Doctrine_Collection getUsers()            Returns the current record's "Users" collection
 * @method Doctrine_Collection getAlternativeType()  Returns the current record's "AlternativeType" collection
 * @method Doctrine_Collection getTypeTemplate()     Returns the current record's "TypeTemplate" collection
 * @method Doctrine_Collection getUserDecisionType() Returns the current record's "UserDecisionType" collection
 * @method Doctrine_Collection getDecision()         Returns the current record's "Decision" collection
 * @method DecisionType        setName()             Sets the current record's "name" value
 * @method DecisionType        setDescription()      Sets the current record's "description" value
 * @method DecisionType        setUsers()            Sets the current record's "Users" collection
 * @method DecisionType        setAlternativeType()  Sets the current record's "AlternativeType" collection
 * @method DecisionType        setTypeTemplate()     Sets the current record's "TypeTemplate" collection
 * @method DecisionType        setUserDecisionType() Sets the current record's "UserDecisionType" collection
 * @method DecisionType        setDecision()         Sets the current record's "Decision" collection
 * 
 * @package    dmp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDecisionType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('decision_type');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             ));

        $this->option('symfony', array(
             'filter' => false,
             'form' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfGuardUser as Users', array(
             'refClass' => 'UserDecisionType',
             'local' => 'type_id',
             'foreign' => 'user_id'));

        $this->hasMany('AlternativeType', array(
             'local' => 'id',
             'foreign' => 'type_id'));

        $this->hasMany('TypeTemplate', array(
             'local' => 'id',
             'foreign' => 'type_id'));

        $this->hasMany('UserDecisionType', array(
             'local' => 'id',
             'foreign' => 'type_id'));

        $this->hasMany('Decision', array(
             'local' => 'id',
             'foreign' => 'type_id'));
    }
}