<?php

/**
 * BaseGraph
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $graph_type_id
 * @property integer $decision_id
 * @property string $description
 * @property GraphType $Type
 * @property Decision $Decision
 * @property Doctrine_Collection $GraphDefinition
 * @property Doctrine_Collection $GraphChanges
 * 
 * @method integer             getGraphTypeId()     Returns the current record's "graph_type_id" value
 * @method integer             getDecisionId()      Returns the current record's "decision_id" value
 * @method string              getDescription()     Returns the current record's "description" value
 * @method GraphType           getType()            Returns the current record's "Type" value
 * @method Decision            getDecision()        Returns the current record's "Decision" value
 * @method Doctrine_Collection getGraphDefinition() Returns the current record's "GraphDefinition" collection
 * @method Doctrine_Collection getGraphChanges()    Returns the current record's "GraphChanges" collection
 * @method Graph               setGraphTypeId()     Sets the current record's "graph_type_id" value
 * @method Graph               setDecisionId()      Sets the current record's "decision_id" value
 * @method Graph               setDescription()     Sets the current record's "description" value
 * @method Graph               setType()            Sets the current record's "Type" value
 * @method Graph               setDecision()        Sets the current record's "Decision" value
 * @method Graph               setGraphDefinition() Sets the current record's "GraphDefinition" collection
 * @method Graph               setGraphChanges()    Sets the current record's "GraphChanges" collection
 * 
 * @package    dmp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGraph extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('graph');
        $this->hasColumn('graph_type_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('decision_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             ));

        $this->option('symfony', array(
             'filter' => false,
             'form' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('GraphType as Type', array(
             'local' => 'graph_type_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Decision', array(
             'local' => 'decision_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('GraphDefinition', array(
             'local' => 'id',
             'foreign' => 'graph_id'));

        $this->hasMany('GraphChanges', array(
             'local' => 'id',
             'foreign' => 'graph_id'));
    }
}