<?php

/**
 * BaseWallPost
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $wall_id
 * @property string $title
 * @property string $content
 * @property string $comment
 * @property string $type
 * @property text $params
 * @property Wall $Wall
 * 
 * @method integer  getWallId()  Returns the current record's "wall_id" value
 * @method string   getTitle()   Returns the current record's "title" value
 * @method string   getContent() Returns the current record's "content" value
 * @method string   getComment() Returns the current record's "comment" value
 * @method string   getType()    Returns the current record's "type" value
 * @method text     getParams()  Returns the current record's "params" value
 * @method Wall     getWall()    Returns the current record's "Wall" value
 * @method WallPost setWallId()  Sets the current record's "wall_id" value
 * @method WallPost setTitle()   Sets the current record's "title" value
 * @method WallPost setContent() Sets the current record's "content" value
 * @method WallPost setComment() Sets the current record's "comment" value
 * @method WallPost setType()    Sets the current record's "type" value
 * @method WallPost setParams()  Sets the current record's "params" value
 * @method WallPost setWall()    Sets the current record's "Wall" value
 * 
 * @package    dmp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWallPost extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('wall_post');
        $this->hasColumn('wall_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('content', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('comment', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('type', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('params', 'text', null, array(
             'type' => 'text',
             ));

        $this->option('symfony', array(
             'filter' => false,
             'form' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Wall', array(
             'local' => 'wall_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}