<?php

/**
 * BaseCriterionPrioritization
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $criterion_head_id
 * @property integer $criterion_tail_id
 * @property float $score
 * @property integer $response_id
 * @property enum $rating_method
 * @property Response $Response
 * @property Criterion $CriterionHead
 * @property Criterion $CriterionTail
 * 
 * @method integer                 getCriterionHeadId()   Returns the current record's "criterion_head_id" value
 * @method integer                 getCriterionTailId()   Returns the current record's "criterion_tail_id" value
 * @method float                   getScore()             Returns the current record's "score" value
 * @method integer                 getResponseId()        Returns the current record's "response_id" value
 * @method enum                    getRatingMethod()      Returns the current record's "rating_method" value
 * @method Response                getResponse()          Returns the current record's "Response" value
 * @method Criterion               getCriterionHead()     Returns the current record's "CriterionHead" value
 * @method Criterion               getCriterionTail()     Returns the current record's "CriterionTail" value
 * @method CriterionPrioritization setCriterionHeadId()   Sets the current record's "criterion_head_id" value
 * @method CriterionPrioritization setCriterionTailId()   Sets the current record's "criterion_tail_id" value
 * @method CriterionPrioritization setScore()             Sets the current record's "score" value
 * @method CriterionPrioritization setResponseId()        Sets the current record's "response_id" value
 * @method CriterionPrioritization setRatingMethod()      Sets the current record's "rating_method" value
 * @method CriterionPrioritization setResponse()          Sets the current record's "Response" value
 * @method CriterionPrioritization setCriterionHead()     Sets the current record's "CriterionHead" value
 * @method CriterionPrioritization setCriterionTail()     Sets the current record's "CriterionTail" value
 * 
 * @package    dmp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCriterionPrioritization extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('criterion_prioritization');
        $this->hasColumn('criterion_head_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('criterion_tail_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('score', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('response_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('rating_method', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'direct rating',
              1 => 'direct float',
              2 => 'forced ranking',
              3 => 'five point scale',
              4 => 'ten point scale',
              5 => 'pairwise comparison',
             ),
             'notnull' => true,
             ));

        $this->option('symfony', array(
             'filter' => false,
             'form' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Response', array(
             'local' => 'response_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Criterion as CriterionHead', array(
             'local' => 'criterion_head_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Criterion as CriterionTail', array(
             'local' => 'criterion_tail_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}