<?php

/**
 * BaseTagFilter
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $decision_id
 * @property integer $tag_id
 * @property Decision $Decision
 * @property Tag $Tag
 * 
 * @method integer   getDecisionId()  Returns the current record's "decision_id" value
 * @method integer   getTagId()       Returns the current record's "tag_id" value
 * @method Decision  getDecision()    Returns the current record's "Decision" value
 * @method Tag       getTag()         Returns the current record's "Tag" value
 * @method TagFilter setDecisionId()  Sets the current record's "decision_id" value
 * @method TagFilter setTagId()       Sets the current record's "tag_id" value
 * @method TagFilter setDecision()    Sets the current record's "Decision" value
 * @method TagFilter setTag()         Sets the current record's "Tag" value
 * 
 * @package    dmp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTagFilter extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tag_filter');
        $this->hasColumn('decision_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('tag_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));


        $this->index('status_filter_decsion_idx', array(
             'fields' => 
             array(
              0 => 'decision_id',
              1 => 'tag_id',
             ),
             'type' => 'unique',
             ));
        $this->option('symfony', array(
             'filter' => false,
             'form' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Decision', array(
             'local' => 'decision_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Tag', array(
             'local' => 'tag_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}