<?php

/**
 * BaseLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property enum $action
 * @property varchar $information
 * @property sfGuardUser $User
 * 
 * @method integer     getUserId()      Returns the current record's "user_id" value
 * @method enum        getAction()      Returns the current record's "action" value
 * @method varchar     getInformation() Returns the current record's "information" value
 * @method sfGuardUser getUser()        Returns the current record's "User" value
 * @method Log         setUserId()      Sets the current record's "user_id" value
 * @method Log         setAction()      Sets the current record's "action" value
 * @method Log         setInformation() Sets the current record's "information" value
 * @method Log         setUser()        Sets the current record's "User" value
 * 
 * @package    dmp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('log');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('action', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'login',
              1 => 'project_create',
              2 => 'folder_create',
              3 => 'item_create',
              4 => 'item_update',
              5 => 'criteria_create',
              6 => 'criteria_update',
              7 => 'survey_create',
              8 => 'survey_update',
              9 => 'survey_answered',
              10 => 'budget_create',
              11 => 'budget_update',
              12 => 'release_create',
              13 => 'release_update',
              14 => 'wall_update',
              15 => 'wall_visit',
              16 => 'roadmap_create',
              17 => 'roadmap_update',
             ),
             'default' => 'login',
             ));
        $this->hasColumn('information', 'varchar', 2000, array(
             'type' => 'varchar',
             'length' => 2000,
             ));

        $this->option('symfony', array(
             'filter' => true,
             'form' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'name' => 'created_at',
              'type' => 'timestamp',
              'format' => 'Y-m-d H:i:s',
             ),
             'updated' => 
             array(
              'disabled' => true,
             ),
             ));
        $this->actAs($timestampable0);
    }
}