<?php

/**
 * BasePlannedAlternativeMeasurement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $role_id
 * @property integer $criterion_id
 * @property integer $alternative_id
 * @property Role $Role
 * @property Criterion $Criterion
 * @property Alternative $Alternative
 * 
 * @method integer                       getRoleId()         Returns the current record's "role_id" value
 * @method integer                       getCriterionId()    Returns the current record's "criterion_id" value
 * @method integer                       getAlternativeId()  Returns the current record's "alternative_id" value
 * @method Role                          getRole()           Returns the current record's "Role" value
 * @method Criterion                     getCriterion()      Returns the current record's "Criterion" value
 * @method Alternative                   getAlternative()    Returns the current record's "Alternative" value
 * @method PlannedAlternativeMeasurement setRoleId()         Sets the current record's "role_id" value
 * @method PlannedAlternativeMeasurement setCriterionId()    Sets the current record's "criterion_id" value
 * @method PlannedAlternativeMeasurement setAlternativeId()  Sets the current record's "alternative_id" value
 * @method PlannedAlternativeMeasurement setRole()           Sets the current record's "Role" value
 * @method PlannedAlternativeMeasurement setCriterion()      Sets the current record's "Criterion" value
 * @method PlannedAlternativeMeasurement setAlternative()    Sets the current record's "Alternative" value
 * 
 * @package    dmp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePlannedAlternativeMeasurement extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('planned_alternative_measurement');
        $this->hasColumn('role_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('criterion_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('alternative_id', 'integer', null, array(
             'type' => 'integer',
             ));


        $this->index('role_criterion_alternative_idx', array(
             'fields' => 
             array(
              0 => 'role_id',
              1 => 'criterion_id',
              2 => 'alternative_id',
             ),
             'type' => 'unique',
             ));
        $this->option('symfony', array(
             'filter' => false,
             'form' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Role', array(
             'local' => 'role_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Criterion', array(
             'local' => 'criterion_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Alternative', array(
             'local' => 'alternative_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}