<?php

/**
 * BaseDomain
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * 
 * @method string getName() Returns the current record's "name" value
 * @method Domain setName() Sets the current record's "name" value
 * 
 * @package    dmp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDomain extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('domain');
        $this->hasColumn('name', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}