<?php

/**
 * BasePopularCriterion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property enum $measurement
 * @property enum $variable_type
 * 
 * @method string           getName()          Returns the current record's "name" value
 * @method string           getDescription()   Returns the current record's "description" value
 * @method enum             getMeasurement()   Returns the current record's "measurement" value
 * @method enum             getVariableType()  Returns the current record's "variable_type" value
 * @method PopularCriterion setName()          Sets the current record's "name" value
 * @method PopularCriterion setDescription()   Sets the current record's "description" value
 * @method PopularCriterion setMeasurement()   Sets the current record's "measurement" value
 * @method PopularCriterion setVariableType()  Sets the current record's "variable_type" value
 * 
 * @package    dmp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePopularCriterion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('popular_criterion');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('measurement', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'direct rating',
              1 => 'direct float',
              2 => 'forced ranking',
              3 => 'five point scale',
              4 => 'ten point scale',
              5 => 'comment',
             ),
             'default' => 'five point scale',
             ));
        $this->hasColumn('variable_type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Benefit',
              1 => 'Cost',
              2 => 'Info',
             ),
             'default' => 'Benefit',
             ));

        $this->option('symfony', array(
             'filter' => false,
             'form' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}