<?php

/**
 * BaseMeasurementMethodType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * 
 * @method string                getName()        Returns the current record's "name" value
 * @method string                getDescription() Returns the current record's "description" value
 * @method MeasurementMethodType setName()        Sets the current record's "name" value
 * @method MeasurementMethodType setDescription() Sets the current record's "description" value
 * 
 * @package    dmp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMeasurementMethodType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('measurement_method_type');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             ));

        $this->option('symfony', array(
             'filter' => false,
             'form' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}