<?php

/**
 * BaseUploadedFile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $mime_type
 * @property string $path
 * @property Doctrine_Collection $Alternative
 * @property Doctrine_Collection $AlternativeUploadedFile
 * @property Doctrine_Collection $Role
 * @property Doctrine_Collection $RoleUploadedFile
 * 
 * @method string              getName()                    Returns the current record's "name" value
 * @method string              getMimeType()                Returns the current record's "mime_type" value
 * @method string              getPath()                    Returns the current record's "path" value
 * @method Doctrine_Collection getAlternative()             Returns the current record's "Alternative" collection
 * @method Doctrine_Collection getAlternativeUploadedFile() Returns the current record's "AlternativeUploadedFile" collection
 * @method Doctrine_Collection getRole()                    Returns the current record's "Role" collection
 * @method Doctrine_Collection getRoleUploadedFile()        Returns the current record's "RoleUploadedFile" collection
 * @method UploadedFile        setName()                    Sets the current record's "name" value
 * @method UploadedFile        setMimeType()                Sets the current record's "mime_type" value
 * @method UploadedFile        setPath()                    Sets the current record's "path" value
 * @method UploadedFile        setAlternative()             Sets the current record's "Alternative" collection
 * @method UploadedFile        setAlternativeUploadedFile() Sets the current record's "AlternativeUploadedFile" collection
 * @method UploadedFile        setRole()                    Sets the current record's "Role" collection
 * @method UploadedFile        setRoleUploadedFile()        Sets the current record's "RoleUploadedFile" collection
 * 
 * @package    dmp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUploadedFile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('uploaded_file');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('mime_type', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('path', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('symfony', array(
             'filter' => false,
             'form' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Alternative', array(
             'refClass' => 'AlternativeUploadedFile',
             'local' => 'uploaded_file_id',
             'foreign' => 'alternative_id'));

        $this->hasMany('AlternativeUploadedFile', array(
             'local' => 'id',
             'foreign' => 'uploaded_file_id'));

        $this->hasMany('Role', array(
             'refClass' => 'RoleUploadedFile',
             'local' => 'uploaded_file_id',
             'foreign' => 'role_id'));

        $this->hasMany('RoleUploadedFile', array(
             'local' => 'id',
             'foreign' => 'uploaded_file_id'));
    }
}