<?php

/**
 * BaseTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property varchar $name
 * @property sfGuardUser $User
 * @property Doctrine_Collection $TagFilter
 * @property Doctrine_Collection $TagDecision
 * @property Doctrine_Collection $TagAlternative
 * @property Doctrine_Collection $TagRelease
 * 
 * @method integer             getUserId()         Returns the current record's "user_id" value
 * @method varchar             getName()           Returns the current record's "name" value
 * @method sfGuardUser         getUser()           Returns the current record's "User" value
 * @method Doctrine_Collection getTagFilter()      Returns the current record's "TagFilter" collection
 * @method Doctrine_Collection getTagDecision()    Returns the current record's "TagDecision" collection
 * @method Doctrine_Collection getTagAlternative() Returns the current record's "TagAlternative" collection
 * @method Doctrine_Collection getTagRelease()     Returns the current record's "TagRelease" collection
 * @method Tag                 setUserId()         Sets the current record's "user_id" value
 * @method Tag                 setName()           Sets the current record's "name" value
 * @method Tag                 setUser()           Sets the current record's "User" value
 * @method Tag                 setTagFilter()      Sets the current record's "TagFilter" collection
 * @method Tag                 setTagDecision()    Sets the current record's "TagDecision" collection
 * @method Tag                 setTagAlternative() Sets the current record's "TagAlternative" collection
 * @method Tag                 setTagRelease()     Sets the current record's "TagRelease" collection
 * 
 * @package    dmp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTag extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tag');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'varchar', 127, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 127,
             ));

        $this->option('symfony', array(
             'filter' => true,
             'form' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('TagFilter', array(
             'local' => 'id',
             'foreign' => 'tag_id'));

        $this->hasMany('TagDecision', array(
             'local' => 'id',
             'foreign' => 'tag_id'));

        $this->hasMany('TagAlternative', array(
             'local' => 'id',
             'foreign' => 'tag_id'));

        $this->hasMany('TagRelease', array(
             'local' => 'id',
             'foreign' => 'tag_id'));
    }
}