<?php

/**
 * BaseGraphChanges
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $graph_id
 * @property decimal $number
 * @property integer $criterion_id
 * @property Graph $Graph
 * @property Criterion $Criterion
 * 
 * @method integer      getGraphId()      Returns the current record's "graph_id" value
 * @method decimal      getNumber()       Returns the current record's "number" value
 * @method integer      getCriterionId()  Returns the current record's "criterion_id" value
 * @method Graph        getGraph()        Returns the current record's "Graph" value
 * @method Criterion    getCriterion()    Returns the current record's "Criterion" value
 * @method GraphChanges setGraphId()      Sets the current record's "graph_id" value
 * @method GraphChanges setNumber()       Sets the current record's "number" value
 * @method GraphChanges setCriterionId()  Sets the current record's "criterion_id" value
 * @method GraphChanges setGraph()        Sets the current record's "Graph" value
 * @method GraphChanges setCriterion()    Sets the current record's "Criterion" value
 * 
 * @package    dmp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGraphChanges extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('graph_changes');
        $this->hasColumn('graph_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('number', 'decimal', 20, array(
             'type' => 'decimal',
             'scale' => 1,
             'length' => 20,
             ));
        $this->hasColumn('criterion_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('symfony', array(
             'filter' => false,
             'form' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Graph', array(
             'local' => 'graph_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Criterion', array(
             'local' => 'criterion_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}