<?php

/**
 * BaseTagRelease
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $tag_id
 * @property integer $release_id
 * @property ProjectRelease $ProjectRelease
 * @property Tag $Tag
 * 
 * @method integer        getTagId()          Returns the current record's "tag_id" value
 * @method integer        getReleaseId()      Returns the current record's "release_id" value
 * @method ProjectRelease getProjectRelease() Returns the current record's "ProjectRelease" value
 * @method Tag            getTag()            Returns the current record's "Tag" value
 * @method TagRelease     setTagId()          Sets the current record's "tag_id" value
 * @method TagRelease     setReleaseId()      Sets the current record's "release_id" value
 * @method TagRelease     setProjectRelease() Sets the current record's "ProjectRelease" value
 * @method TagRelease     setTag()            Sets the current record's "Tag" value
 * 
 * @package    dmp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTagRelease extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tag_release');
        $this->hasColumn('tag_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('release_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('symfony', array(
             'filter' => true,
             'form' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ProjectRelease', array(
             'local' => 'release_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Tag', array(
             'local' => 'tag_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}