<?php

/**
 * BaseFolder
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $user_id
 * @property boolean $deletable
 * @property enum $type
 * @property boolean $open
 * @property sfGuardUser $User
 * @property Doctrine_Collection $Decisions
 * @property Doctrine_Collection $Roadmaps
 * 
 * @method string              getName()      Returns the current record's "name" value
 * @method integer             getUserId()    Returns the current record's "user_id" value
 * @method boolean             getDeletable() Returns the current record's "deletable" value
 * @method enum                getType()      Returns the current record's "type" value
 * @method boolean             getOpen()      Returns the current record's "open" value
 * @method sfGuardUser         getUser()      Returns the current record's "User" value
 * @method Doctrine_Collection getDecisions() Returns the current record's "Decisions" collection
 * @method Doctrine_Collection getRoadmaps()  Returns the current record's "Roadmaps" collection
 * @method Folder              setName()      Sets the current record's "name" value
 * @method Folder              setUserId()    Sets the current record's "user_id" value
 * @method Folder              setDeletable() Sets the current record's "deletable" value
 * @method Folder              setType()      Sets the current record's "type" value
 * @method Folder              setOpen()      Sets the current record's "open" value
 * @method Folder              setUser()      Sets the current record's "User" value
 * @method Folder              setDecisions() Sets the current record's "Decisions" collection
 * @method Folder              setRoadmaps()  Sets the current record's "Roadmaps" collection
 * 
 * @package    dmp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFolder extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('folder');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('deletable', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'project',
              1 => 'roadmap',
             ),
             'default' => 'project',
             ));
        $this->hasColumn('open', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));

        $this->option('symfony', array(
             'filter' => false,
             'form' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Decision as Decisions', array(
             'local' => 'id',
             'foreign' => 'folder_id'));

        $this->hasMany('Roadmap as Roadmaps', array(
             'local' => 'id',
             'foreign' => 'folder_id'));
    }
}