<?php

/**
 * BaseRoleUploadedFile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $role_id
 * @property integer $uploaded_file_id
 * @property Role $Role
 * @property UploadedFile $UploadedFile
 * 
 * @method integer          getRoleId()           Returns the current record's "role_id" value
 * @method integer          getUploadedFileId()   Returns the current record's "uploaded_file_id" value
 * @method Role             getRole()             Returns the current record's "Role" value
 * @method UploadedFile     getUploadedFile()     Returns the current record's "UploadedFile" value
 * @method RoleUploadedFile setRoleId()           Sets the current record's "role_id" value
 * @method RoleUploadedFile setUploadedFileId()   Sets the current record's "uploaded_file_id" value
 * @method RoleUploadedFile setRole()             Sets the current record's "Role" value
 * @method RoleUploadedFile setUploadedFile()     Sets the current record's "UploadedFile" value
 * 
 * @package    dmp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRoleUploadedFile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('role_uploaded_file');
        $this->hasColumn('role_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('uploaded_file_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('symfony', array(
             'filter' => false,
             'form' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Role', array(
             'local' => 'role_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('UploadedFile', array(
             'local' => 'uploaded_file_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}