<?php

/**
 * BaseProjectReleaseAlternative
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $release_id
 * @property integer $alternative_id
 * @property decimal $value
 * @property ProjectRelease $ProjectRelease
 * @property Alternative $Alternative
 * 
 * @method integer                   getReleaseId()      Returns the current record's "release_id" value
 * @method integer                   getAlternativeId()  Returns the current record's "alternative_id" value
 * @method decimal                   getValue()          Returns the current record's "value" value
 * @method ProjectRelease            getProjectRelease() Returns the current record's "ProjectRelease" value
 * @method Alternative               getAlternative()    Returns the current record's "Alternative" value
 * @method ProjectReleaseAlternative setReleaseId()      Sets the current record's "release_id" value
 * @method ProjectReleaseAlternative setAlternativeId()  Sets the current record's "alternative_id" value
 * @method ProjectReleaseAlternative setValue()          Sets the current record's "value" value
 * @method ProjectReleaseAlternative setProjectRelease() Sets the current record's "ProjectRelease" value
 * @method ProjectReleaseAlternative setAlternative()    Sets the current record's "Alternative" value
 * 
 * @package    dmp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProjectReleaseAlternative extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('project_release_alternative');
        $this->hasColumn('release_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('alternative_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('value', 'decimal', 20, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 20,
             ));

        $this->option('symfony', array(
             'filter' => false,
             'form' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ProjectRelease', array(
             'local' => 'release_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Alternative', array(
             'local' => 'alternative_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}