<?php

/**
 * BaseInterfaceLabel
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $type
 * @property string $singular
 * @property string $plural
 * @property sfGuardUser $User
 * 
 * @method integer        getUserId()   Returns the current record's "user_id" value
 * @method integer        getType()     Returns the current record's "type" value
 * @method string         getSingular() Returns the current record's "singular" value
 * @method string         getPlural()   Returns the current record's "plural" value
 * @method sfGuardUser    getUser()     Returns the current record's "User" value
 * @method InterfaceLabel setUserId()   Sets the current record's "user_id" value
 * @method InterfaceLabel setType()     Sets the current record's "type" value
 * @method InterfaceLabel setSingular() Sets the current record's "singular" value
 * @method InterfaceLabel setPlural()   Sets the current record's "plural" value
 * @method InterfaceLabel setUser()     Sets the current record's "User" value
 * 
 * @package    dmp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInterfaceLabel extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('interface_label');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('type', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('singular', 'string', 64, array(
             'type' => 'string',
             'length' => 64,
             ));
        $this->hasColumn('plural', 'string', 64, array(
             'type' => 'string',
             'length' => 64,
             ));

        $this->option('symfony', array(
             'filter' => false,
             'form' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}