indexSuccess:
  javascripts:
    - tooltip.js
    - /libs/jquery-colorbox/jquery.colorbox-min.js?v=1.5.14
    - /libs/timelinejs/js/storyjs-embed.js?v=2.35.2&m=1
  stylesheets:
    - /libs/jquery-colorbox/colorbox.css?v=1.5.14