<?php

/**
 * AlternativeTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlternativeTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AlternativeTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AlternativeType');
    }
}