<?php

/**
 * AlternativeLinkTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlternativeLinkTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return AlternativeLinkTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('AlternativeLink');
  }
}