<?php

/**
 * AlternativeUploadedFileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlternativeUploadedFileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AlternativeUploadedFileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AlternativeUploadedFile');
    }
}