<?php

/**
 * AnalyzeCollapseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AnalyzeCollapseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AnalyzeCollapseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AnalyzeCollapse');
    }
}