<?php

/**
 * CriteriaTemplate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    dmp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class CriteriaTemplate extends BaseCriteriaTemplate
{
  public function getRowData()
  {
    $routing = sfContext::getInstance()->getRouting();
    return array(
      'id'  => $this->id,
      'name' => $this->name,
      'type' => $this->variable_type,
      'measurement' => $this->measurement,
      'fetch_url' => $routing->generate('user_profile\criteriaTemplateFetch', array('id' => $this->id)),
      'edit_url' => $routing->generate('user_profile\criteriaTemplateEdit', array('id' => $this->id)),
      'delete_url' => $routing->generate('user_profile\criteriaTemplateDelete')
    );
  }
}
