<?php

/**
 * CriteriaTemplateTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CriteriaTemplateTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return CriteriaTemplateTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('CriteriaTemplate');
  }

  public function getListJSON(TypeTemplate $template)
  {
    /** @var CriteriaTemplate[] $templates */
    $templates = $this->createQuery('ct')
      ->where('ct.template_id = ?', $template->id)
      ->execute();

    $result = array();
    foreach ($templates as $template) {
      $result[] = $template->getRowData();
    }

    return json_encode($result);
  }
}