<?php

/**
 * DecisionTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DecisionTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return DecisionTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DecisionType');
    }
}