<?php

/**
 * DomainTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DomainTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return DomainTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Domain');
  }

}