<?php

/**
 * Folder
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    dmp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Folder extends BaseFolder
{
  const TYPE_PROJECT = 'project';

  const TYPE_ROADMAP = 'roadmap';

  /**
   * Returns an instance of this class.
   *
   * @return FolderTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Folder');
  }

  /**
   * @return array
   */
  public function getRowData($type = 'project')
  {
    $routing = sfContext::getInstance()->getRouting();

    $projects = array();
    foreach ($this->Decisions as $decision) {
      $projects[] = $decision->getRowData();
    }

    $roadmaps = array();
    foreach ($this->Roadmaps as $roadmap) {
      $roadmaps[] = $roadmap->getRowData();
    }

    return array(
      'id'                        => $this->id,
      'name'                      => $this->name,
      'edit_url'                  => $routing->generate('decision\editFolder', array('id' => $this->id)),
      'delete_url'                => $type == 'project' ? $routing->generate('decision\deleteFolder') : $routing->generate('roadmap\deleteFolder'),
      'project_add_to_folder_url' => $routing->generate('decision\addToFolder'),
      'roadmap_add_to_folder_url' => $routing->generate('roadmap\addToFolder'),
      'projects'                  => $projects,
      'roadmaps'                  => $roadmaps,
      'deletable'                 => $this->deletable,
      'open'                      => $this->open,
      'state_url'                 => $routing->generate('decision\updateFolderState', array('id' => $this->id)),
    );
  }
}
