<?php

/**
 * GraphTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GraphTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GraphTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Graph');
    }
}