<?php

/**
 * GraphChangesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GraphChangesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GraphChangesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GraphChanges');
    }
}