<?php

/**
 * GraphTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GraphTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GraphTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GraphType');
    }
}