<?php

/**
 * GraphDefinitionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GraphDefinitionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GraphDefinitionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GraphDefinition');
    }
}