<?php

/**
 * InterfaceLabelTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InterfaceLabelTable extends Doctrine_Table
{

  const ITEM_TYPE    = 1;
  const PROJECT_TYPE = 2;
  const FOLDER_TYPE  = 3;
  const RELEASE_TYPE = 4;

  private $data = array();

  private $loaded = false;

  private $default_data = array(
    self::ITEM_TYPE => array(
      'singular' => 'item',
      'plural'   => 'items',
    ),
    self::PROJECT_TYPE => array(
      'singular' => 'project',
      'plural'   => 'project',
    ),
    self::FOLDER_TYPE => array(
      'singular' => 'folder',
      'plural'   => 'folders',
    ),
    self::RELEASE_TYPE => array(
      'singular' => 'release',
      'plural'   => 'releases',
    ),
  );

  /**
   * Returns an instance of this class.
   *
   * @return InterfaceLabelTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('InterfaceLabel');
  }

  /**
   * @param sfGuardUser $user
   */
  private function load_data(sfGuardUser $user)
  {
    $rows = $this->createQuery('il')
      ->whereIn('il.user_id', sfGuardUserTable::getInstance()->getUsersInTeamIDs($user))
      ->fetchArray();

    $this->data = array();

    foreach ($rows as $row) {
      $this->data[$row['type']] = array(
        'singular' => $row['singular'],
        'plural'   => $row['plural'],
      );
    }

    $this->loaded = true;
  }

  /**
   * @param sfGuardUser $user
   * @param $key
   * @param bool $plural
   * @return mixed
   */
  public function get(sfGuardUser $user, $key, $plural = false)
  {
    if (!$this->loaded) { $this->load_data($user); }

    if (array_key_exists($key, $this->data) && ($this->data[$key][$this->getKey($plural)] !== null)) {
      return $this->data[$key][$this->getKey($plural)];
    }else{
      return $this->default_data[$key][$this->getKey($plural)];
    }
  }

  /**
   * @param $plural
   * @return string
   */
  private function getKey($plural)
  {
    if ($plural) {
      return 'plural';
    }
    return 'singular';
  }
}