<?php

/**
 * LogicalFilter
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    dmp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class LogicalFilter extends BaseLogicalFilter
{
  public function __toString()
  {
    return $this->Criterion->name . ' ' . $this->logical_operator . ' ' . $this->value;
  }

  public function postInsert($event)
  {
    Doctrine_Query::create()->delete('Graph')->where('decision_id = ?', $this->decision_id)->execute();
  }
}
