<?php

/**
 * LogicalFilterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LogicalFilterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return LogicalFilterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LogicalFilter');
    }
}