<?php

/**
 * MeasurementMethodTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MeasurementMethodTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MeasurementMethodTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MeasurementMethodType');
    }
}