<?php

/**
 * PlannedCriterionPrioritization
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    dmp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PlannedCriterionPrioritization extends BasePlannedCriterionPrioritization
{
  public function getAPIData()
  {
    return array(
      'id' => $this->id,
      'criterion_id' => $this->criterion_id
    );
  }
}
