<?php

/**
 * PlannedCriterionPrioritizationTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlannedCriterionPrioritizationTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return PlannedCriterionPrioritizationTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PlannedCriterionPrioritization');
  }

  public function getListForAPI(sfGuardUser $user, $role_id)
  {
    /** @var PlannedCriterionPrioritization[] $plannedCriteria */
    $plannedCriteria = $this->createQuery('pcp')
      ->leftJoin('pcp.Role r')
      ->leftJoin('r.Decision d')
      ->leftJoin('d.User u')
      ->leftJoin('u.TeamMember tm')
      ->whereIn('d.user_id', sfGuardUserTable::getInstance()->getUsersInTeamIDs($user))
      ->andWhere('pcp.role_id = ?', $role_id)
      ->execute();

    $result = array();
    foreach ($plannedCriteria as $plannedCriterion) {
      $result[] = $plannedCriterion->getAPIData();
    }

    return $result;
  }

  /**
   * @param sfGuardUser $user
   * @param $id
   * @return PlannedCriterionPrioritization
   */
  public function getOneForUser(sfGuardUser $user, $id)
  {
    return $this->createQuery('pcp')
      ->leftJoin('pcp.Role r')
      ->leftJoin('r.Decision d')
      ->leftJoin('d.User u')
      ->leftJoin('u.TeamMember tm')
      ->whereIn('d.user_id', sfGuardUserTable::getInstance()->getUsersInTeamIDs($user))
      ->andWhere('pcp.id = ?', $id)
      ->fetchOne();
  }
}