<?php

/**
 * PlannedAlternativeMeasurement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    dmp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PlannedAlternativeMeasurement extends BasePlannedAlternativeMeasurement
{
  private
    $counter = 0,
    $score_sum = 0;

  public function addScore($score)
  {
    $this->score_sum += $score;
    $this->counter++;
  }

  public function getAverage()
  {
    return $this->score_sum / $this->counter;
  }

  public function resetScore()
  {
    $this->score_sum = 0;
    $this->counter = 0;
  }

  public function getAPIData()
  {
    return array(
      'id' => $this->id,
      'alternative_id' => $this->alternative_id,
      'criterion_id' => $this->criterion_id
    );
  }
}
