<?php

/**
 * PopularCriterionTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PopularCriterionTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return PopularCriterionTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PopularCriterion');
  }

  /**
   * @return Doctrine_Collection|PopularCriterion[]
   */
  public function getDashboardDefaultList()
  {
    return $this->createQuery('pc')->whereIn('pc.id', array(1, 2, 4, 6))->execute();
  }
}