<?php

/**
 * ProjectReleaseAlternativeTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProjectReleaseAlternativeTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return ProjectReleaseAlternativeTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('ProjectReleaseAlternative');
  }
}