<?php

/**
 * ProjectRelease
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    dmp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ProjectRelease extends BaseProjectRelease
{
  public function updateValue()
  {
    $this->value = Doctrine_Query::create()
      ->select('SUM(value) AS sum')
      ->from('ProjectReleaseAlternative')
      ->where('release_id = ?', $this->id)
      ->groupBy('release_id')
      ->fetchOne()->sum;
  }

  /**
   * @return array
   */
  public function getRowData()
  {
    sfContext::getInstance()->getConfiguration()->loadHelpers('Url');
    sfContext::getInstance()->getConfiguration()->loadHelpers('Escaping');

    $routing = sfContext::getInstance()->getRouting();
    return array(
        '_element_type'       => 'release',
        'id'                  => $this->id,
        'name'                => $this->name,
        'status'              => $this->status,
        'edit_url'            => $routing->generate('planner2\editRelease', array('id' => $this->id)),
        'delete_url'          => $routing->generate('planner2\deleteRelease')
    );
  }
}
