<?php

/**
 * ProjectReleaseTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProjectReleaseTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return ProjectReleaseTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('ProjectRelease');
  }

  public function getList($decision_id)
  {
    return $this->createQuery('r')
      ->leftJoin('r.ProjectReleaseAlternative ra')
      ->leftJoin('ra.Alternative a')
      ->where('r.decision_id = ?', $decision_id)
      ->execute();
  }
}