<?php

/**
 * PromoCodeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PromoCodeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PromoCodeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PromoCode');
    }
}