<?php

/**
 * ResponseTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ResponseTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return ResponseTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Response');
  }

  /**
   * @param sfGuardUser $user
   * @param int $decision_id
   * @return Response|false
   */
  public function getOneForDashboard(sfGuardUser $user, $decision_id)
  {
    return $this->createQuery('rs')
      ->leftJoin('rs.Role r')
      ->leftJoin('r.Decision d')
      ->leftJoin('d.User u')
      ->leftJoin('u.TeamMember tm')
      ->whereIn('d.user_id', sfGuardUserTable::getInstance()->getUsersInTeamIDs($user))
      ->andWhere('r.decision_id = ? AND r.dashboard = 1 AND rs.email_address = "dashboard"', $decision_id)
      ->fetchOne();
  }

  public function getListForAPI(sfGuardUser $user, $decision_id)
  {
    /** @var Response[] $responses */
    $responses = $this->createQuery('r')
      ->leftJoin('r.Decision d')
      ->leftJoin('d.User u')
      ->leftJoin('u.TeamMember tm')
      ->whereIn('d.user_id', sfGuardUserTable::getInstance()->getUsersInTeamIDs($user))
      ->andWhere('r.decision_id = ?', $decision_id)
      ->execute();

    $result = array();
    foreach ($responses as $response) {
      $result[] = $response->getAPIData();
    }

    return $result;
  }

  /**
   * @param sfGuardUser $user
   * @param $id
   * @return Role
   */
  public function getOneForUser(sfGuardUser $user, $id)
  {
    return $this->createQuery('r')
      ->leftJoin('r.Decision d')
      ->leftJoin('d.User u')
      ->leftJoin('u.TeamMember tm')
      ->whereIn('d.user_id', sfGuardUserTable::getInstance()->getUsersInTeamIDs($user))
      ->andWhere('r.id = ?', $id)
      ->fetchOne();
  }
}