<?php

/**
 * Roadmap
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    dmp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Roadmap extends BaseRoadmap
{
  /** @var array */
  private $decisions = array();

  /**
   * @param $decision_id
   * @return bool
   */
  public function hasDecision($decision_id)
  {
    return array_key_exists($decision_id, $this->decisions);
  }

  public function loadDecisions()
  {
    /** @var RoadmapDecision[]|Doctrine_Collection $collection */
    $collection = Doctrine::getTable('RoadmapDecision')->findBy('roadmap_id', $this->id);
    foreach ($collection as $roadmap_decision) {
      $this->decisions[$roadmap_decision->getDecisionId()] = true;
    }
  }

  /**
   * @param $decision
   */
  public function addDecision($decision){
    $new_roadmap_decision = new RoadmapDecision();
    $new_roadmap_decision->setDecisionId($decision);
    $this->RoadmapDecision->add($new_roadmap_decision);
    $this->decisions[$decision] = true;
  }

  /**
   * @param $event
   */
  public function preInsert($event)
  {
    if (!$this->user_id) {
      $this->user_id = sfContext::getInstance()->getUser()->getGuardUser()->id;
    }

    $token = substr(md5(uniqid()), 0, 6);
    while (RoadmapTable::getInstance()->findOneBy('token', $token)) {
      $token = substr(md5(uniqid()), 0, 6);
    }
    $this->token = $token;
  }

  public function preSave($event)
  {
    if (!$this->folder_id) {
      $this->folder_id = Folder::getInstance()->getNotDeletableForUser(sfContext::getInstance()->getUser()->getGuardUser(), Folder::TYPE_ROADMAP)->getId();
    }

    $log = new Log();
    $log->injectDataAndPersist($this, sfContext::getInstance()->getUser()->getGuardUser(), array('action' => $this->isNew() ? 'new' : 'edit'));
  }

  /**
   * @return array
   */
  public function getRowData()
  {
    $routing = sfContext::getInstance()->getRouting();

    return array(
      '_element_type' => 'roadmap',
      'id'            => $this->id,
      'name'          => $this->name,
      'displayed_name'=> $this->getDisplayedName($routing->generate('roadmap\timeline', array('id' => $this->id))),
      'description'   => $this->description,
      'active'        => $this->active,
      'url'           => sfContext::getInstance()->getConfiguration()->generateFrontendUrl('roadmapview', array('token' => $this->token)),
      'link'          => sfContext::getInstance()->getConfiguration()->generateFrontendUrl('roadmapview', array('token' => $this->token)),
//      'dashboard_url' => $routing->generate('roadmap\dashboard', array('id' => $this->id)),
      'timeline_url'  => $routing->generate('roadmap\timeline', array('id' => $this->id)),
      'fetch_url'     => $routing->generate('roadmap\fetch', array('id' => $this->id)),
      'edit_url'      => $routing->generate('roadmap\edit', array('id' => $this->id)),
      'delete_url'    => $routing->generate('roadmap\delete')
    );
  }

  private function getDisplayedName($timeline_url){
    return '<b>
      <i class="glyphicon glyphicon-align-justify help-tip" style="cursor:move" data-toggle="tooltip" data-placement="right" title="Press down to move."></i><a style="margin-left: 5px;" href="' . $timeline_url . '">' . $this->name . '</a>
    </b>
    <div class="row-tools">
      <small>
        <div style="display:none;" class="element-id" data-id="' . $this->id . '"></div>
        <a href="javascript:void(0)" data-id="' . $this->id . '" class="edit_roadmap"><i class="fa fa-pencil-square-o"></i> Edit</a>
      </small>
    </div>';
  }

  public function getOrderedRoadmapDecision(){
    return Doctrine_Core::getTable('RoadmapDecision')->createQuery('rd')
      ->leftJoin('rd.Decision d')
      ->where('rd.roadmap_id = ?', $this->getId())
      ->orderBy('d.start_date DESC')
      ->execute();
  }
}
