<?php

/**
 * RoadmapDecisionTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RoadmapDecisionTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object RoadmapDecisionTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('RoadmapDecision');
  }

  public function getRoadmapDecisionForUser(sfGuardUser $user, $roadmap_decision_id)
  {
    return $this->createQuery('rd')
      ->leftJoin('rd.Roadmap r')
      ->leftJoin('r.User u')
      ->leftJoin('u.TeamMember tm')
      ->whereIn('r.user_id', sfGuardUserTable::getInstance()->getUsersInTeamIDs($user))
      ->andWhere('rd.id = ?', $roadmap_decision_id)
      ->fetchOne();
  }
}