<?php

/**
 * RoadmapTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RoadmapTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return RoadmapTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Roadmap');
  }

  /**
   * @param sfGuardUser $user
   * @param $roadmap_id
   * @return Roadmap
   */
  public function getRoadmapForUser(sfGuardUser $user, $roadmap_id)
  {
    return $this->createQuery('r')
      ->leftJoin('r.User u')
      ->leftJoin('u.TeamMember tm')
      ->whereIn('r.user_id', sfGuardUserTable::getInstance()->getUsersInTeamIDs($user))
      ->andWhere('r.id = ?', $roadmap_id)
      ->fetchOne();
  }

  public function getForUserJSON(sfGuardUser $user)
  {
    /** @var Roadmap[] $roadmaps */
    $roadmaps = $this->createQuery('r')
      ->leftJoin('r.User u')
      ->leftJoin('u.TeamMember tm')
      ->whereIn('r.user_id', sfGuardUserTable::getInstance()->getUsersInTeamIDs($user))
      ->andWhere('r.folder_id IS NULL')
      ->execute();

    $result = array();
    foreach ($roadmaps as $roadmap) {
      $result[] = $roadmap->getRowData();
    }

    return json_encode($result);
  }

  /**
   * @param sfGuardUser $user
   * @return Roadmap[]
   */
  public function getForUser(sfGuardUser $user)
  {
    return $this->createQuery('r')
      ->leftJoin('r.User u')
      ->leftJoin('u.TeamMember tm')
      ->whereIn('r.user_id', sfGuardUserTable::getInstance()->getUsersInTeamIDs($user))
      ->andWhere('r.folder_id IS NULL')
      ->execute();
  }
}