<?php

/**
 * RoleTemplateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RoleTemplateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RoleTemplateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RoleTemplate');
    }
}