<?php

/**
 * RoleFilter
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    dmp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class RoleFilter extends BaseRoleFilter
{
  public function postInsert($event)
  {
    Doctrine_Query::create()->delete('Graph')->where('decision_id = ?', $this->decision_id)->execute();
  }
}
