<?php

/**
 * RoleFilterTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RoleFilterTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return RoleFilterTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('RoleFilter');
  }
}