<?php

/**
 * RoleUploadedFileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RoleUploadedFileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RoleUploadedFileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RoleUploadedFile');
    }
}