<?php

/**
 * ScriptsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScriptsTable extends Doctrine_Table
{
  static public $singleton = null;

  public function getSingleton()
  {
    if (!self::$singleton) {
      if (!self::$singleton = $this->createQuery("r")->fetchOne()) {
        $scrips = new Scripts();
        $scrips->save();

        self::$singleton = $scrips;
      }
    }

    return self::$singleton;
  }
}