<?php

/**
 * StatusFilterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StatusFilterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StatusFilterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StatusFilter');
    }
}