<?php

/**
 * TagAlternativeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TagAlternativeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TagAlternativeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TagAlternative');
    }
}