<?php

/**
 * TagDecisionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TagDecisionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TagDecisionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TagDecision');
    }
}