<?php

/**
 * TagFilterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TagFilterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TagFilterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TagFilter');
    }
}