<?php

/**
 * TagReleaseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TagReleaseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TagReleaseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TagRelease');
    }
}