<?php

/**
 * TokenTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TokenTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return TokenTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Token');
  }
}