<?php

/**
 * TypeTemplateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TypeTemplateTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return TypeTemplateTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('TypeTemplate');
  }

  /**
   * @param $user_id
   * @return mixed|string|void
   */
  public function getListJSON($user_id)
  {
    /** @var TypeTemplate[] $templates */
    $templates = $this->createQuery('tt')
      ->leftJoin('tt.Type t')
      ->where('tt.user_id = ? or tt.user_id is null', $user_id)
      ->execute();

    $result = array();
    foreach ($templates as $template) {
      $result[] = $template->getRowData();
    }

    return json_encode($result);
  }
}