<?php

/**
 * UploadedFile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    dmp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class UploadedFile extends BaseUploadedFile
{
  public function getResponseObject()
  {
    $controller =  sfContext::getInstance()->getController();
    $file = new stdClass();
    $file->name = $this->name;
    $file->size = filesize($this->getAbsolutePath());
    $file->delete_url = $controller->genUrl(array('sf_route' => 'uploaded_file\delete', 'id' => $this->id));
    $file->delete_type = 'DELETE';
    $file->url = $controller->genUrl(array('sf_route' => 'uploaded_file\download', 'id' => $this->id));

    return $file;
  }

  public function postDelete($event)
  {
    // Remove file
    if ($this->getAbsolutePath() && file_exists($this->getAbsolutePath())) {
      unlink($this->getAbsolutePath());
    }
  }

  public function getAbsolutePath()
  {
    return sfConfig::get('sf_upload_dir') .  $this->path;
  }

  public function isImage()
  {
    return in_array($this->mime_type, array('image/png', 'image/jpeg', 'image/gif'));
  }
}
