<?php

/**
 * UploadedFileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UploadedFileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UploadedFileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UploadedFile');
    }
}