<?php

/**
 * WallTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WallTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return WallTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Wall');
    }
}