<?php

/**
 * WallPostTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WallPostTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return WallPostTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('WallPost');
  }
}