# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:
    - /libs/bootstrap/css/bootstrap.min.css?v=3.3.2
    - dist/main.css?v=5
    - /libs/animate/animate.min.css?v=3.1.0
    - /libs/font-awesome/css/font-awesome.min.css?v=4.2.0

  javascripts:
    - /libs/jquery/jquery-2.1.1.min.js
    - /libs/bootstrap/js/bootstrap.min.js?v=3.3.2
    - /libs/jquery-scrollTo/jquery.scrollTo.min.js?v=1.4.14
    - application.js?v=2
    #- google_analytics.js
    - { '//html5shim.googlecode.com/svn/trunk/html5.js': { condition: lt IE 9 } }
    - //cdnjs.cloudflare.com/ajax/libs/wow/0.1.12/wow.min.js


  has_layout:     true
  layout:         layout
