indexSuccess:
  javascripts:
    - /libs/jquery-ui/jquery-ui.min.js?v=1.11.2
    - /libs/underscore/underscore-min.js?v=1.6.0
    - /libs/backbone/backbone-min.js?v=1.1.2
    - models/row_object.js?v=3
    - views/row_edit.js?v=8
    - views_new/data_table_view.js?v=1
    - /libs/jquery-data-table/jquery.dataTables.min.js?v=1.10.5
    - /libs/jquery-data-table/dataTables.fixedColumns.min.js?v=3.0.3
    - /libs/jquery-data-table/dt_bootstrap.js?v=1.10.4
    - /libs/zeroclipboard/ZeroClipboard.min.js?v=2.2.0
    - /libs/bootstrap-switch/bootstrap-switch.min.js?v=3.3.2
  stylesheets:
    - /libs/jquery-data-table/dt_bootstrap.css?v=1.10.4
    - /libs/bootstrap-switch/bootstrap-switch.min.css?v=3.3.2
    - /libs/jquery-data-table/css/jquery.dataTables.part.css?v=1.10.5