<?php

/**
 * sfGuardUserTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserTable extends PluginsfGuardUserTable
{
  /**
   * Returns an instance of this class.
   *
   * @return sfGuardUserTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('sfGuardUser');
  }

  /**
   * @param sfGuardUser $user
   * @return Doctrine_Query
   */
  public function getUsersInTeamQuery(sfGuardUser $user)
  {
    return $this->createQuery('u')
      ->leftJoin('u.TeamMember tm')
      ->where('tm.manager_id = ?', $user->id)
      ->orWhere('u.id = ?', $user->id);
  }

  /**
   * @param sfGuardUser $user
   * @return array
   */
  public function getUsersInTeamIDs(sfGuardUser $user)
  {
    $ids = array();
    $ids[] = $user->getId();

    $q = $this->createQuery('u')
      ->leftJoin('u.TeamMember tm')
      ->where('tm.manager_id = ?', $user->getId());

    $team_manager = $this->userTeamManager($user);
    if ($team_manager) {
      $ids[] = $team_manager;
      $q->orWhere('tm.manager_id = ?', $team_manager);
    }


    $users = $q->execute();
    foreach ($users as $user) {
      $ids[] = $user->getId();
    }

    return array_unique($ids);
  }

  /**
   * @param sfGuardUser $user
   * @return bool
   */
  public function userTeamManager(sfGuardUser $user)
  {
    $q = $this->createQuery('u')
      ->leftJoin('u.TeamMember tm')
      ->where('tm.user_id = ?', $user->id)
      ->fetchOne();

    if ($q){
      return $q->TeamMember[0]->getManagerId();
    }else{
      return false;
    }
  }

  /**
   * @param string $token
   * @return mixed
   */
  public function getUserByToken($token)
  {
    return $this->createQuery('u')
      ->leftJoin('u.Tokens t')
      ->where('t.token_key = ?', $token)
      ->fetchOne();
  }
}