<?php

/**
 * TeamMemberTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TeamMemberTable extends PluginTeamMemberTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object TeamMemberTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TeamMember');
    }
}