<?php

/**
 * PaymentTransactionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PaymentTransactionTable extends PluginPaymentTransactionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PaymentTransactionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PaymentTransaction');
    }
}