<?php

/**
 * BaseTeamMember
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $manager_id
 * @property integer $user_id
 * @property sfGuardUser $Manager
 * @property sfGuardUser $User
 * 
 * @method integer     getManagerId()  Returns the current record's "manager_id" value
 * @method integer     getUserId()     Returns the current record's "user_id" value
 * @method sfGuardUser getManager()    Returns the current record's "Manager" value
 * @method sfGuardUser getUser()       Returns the current record's "User" value
 * @method TeamMember  setManagerId()  Sets the current record's "manager_id" value
 * @method TeamMember  setUserId()     Sets the current record's "user_id" value
 * @method TeamMember  setManager()    Sets the current record's "Manager" value
 * @method TeamMember  setUser()       Sets the current record's "User" value
 * 
 * @package    dmp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTeamMember extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('team_member');
        $this->hasColumn('manager_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('symfony', array(
             'form' => true,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as Manager', array(
             'local' => 'manager_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}