generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Scripts
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          scripts
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:
        delete: false
      fields:  ~
      list:    ~
      filter:
        class: false
      form:    ~
      edit:    ~
      new:     ~
