<?php

/**
 * PluginPaymentTransaction
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginPaymentTransaction extends BasePaymentTransaction
{
  /**
   * Calculate new active period
   * @param type $event 
   */
  public function preSave($event)
  {
    if (!$this->refnumber)
    {
      $this->refnumber = self::generateLocalRefNumber();
    }
  }


  /**
   * @return string
   */
  public static function generateLocalRefNumber()
  {
    //get the Transaction number in current month
    $res = Doctrine_Query::create()->from('PaymentTransaction')
            ->select('COUNT(id)+1 AS cnt')
            ->where('MONTH(created_at) = MONTH(NOW()) OR MONTH(date_payed) = MONTH(NOW())')
            ->fetchOne();

    return date('Y').date('m').str_pad(substr($res->cnt, -3), 3, '0', STR_PAD_LEFT);
  }

  public static function getPriceList()
  {
    return array(
      'basic' => 19,
      'pro' => 99,
      'enterprise' => 499
    );
  }
}