<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddExternalIdToDecision extends Doctrine_Migration_Base
{
    public function up()
    {
      $this->addColumn('decision', 'external_id', 'varchar', '50');
    }

    public function down()
    {
      $this->removeColumn('decision', 'external_id');
    }
}