<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddLightToAccountType extends Doctrine_Migration_Base
{
    public function up()
    {
      $this->changeColumn('sf_guard_user', 'account_type', 'enum', '',
        array(
          'values'  =>
            array(
              0 => 'Trial',
              1 => 'Light',
              2 => 'Basic',
              3 => 'Pro',
              4 => 'Enterprise'
            ),
          'default' => 'Trial',
        ));

      $this->changeColumn('promo_code', 'account_type', 'enum', '',
        array(
          'values'  =>
            array(
              0 => 'Trial',
              1 => 'Light',
              2 => 'Basic',
              3 => 'Pro',
              4 => 'Enterprise'
            ),
          'default' => 'Trial',
        ));
    }

    public function down()
    {
      $this->changeColumn('sf_guard_user', 'account_type', 'enum', '',
        array(
          'values'  =>
            array(
              0 => 'Trial',
              1 => 'Basic',
              2 => 'Pro',
              3 => 'Enterprise'
            ),
          'default' => 'Trial',
        ));

      $this->changeColumn('promo_code', 'account_type', 'enum', '',
        array(
          'values'  =>
            array(
              0 => 'Trial',
              1 => 'Basic',
              2 => 'Pro',
              3 => 'Enterprise'
            ),
          'default' => 'Trial',
        ));
    }
}