<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddDefaultColorToProjects extends Doctrine_Migration_Base
{
    public function up()
    {
      $this->changeColumn('decision', 'color', 'varchar', 8, array('default' => '#CCCCCC'));
    }

    public function postUp(){
      Doctrine_Query::create()
        ->update('Decision d')
        ->set('d.color', '?', '#CCCCCC')
        ->where('d.color is NULL')
        ->execute();
    }

    public function down()
    {
      $this->changeColumn('decision', 'color', 'varchar', 8, array('default' => null));
    }
}