<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddSfCombine extends Doctrine_Migration_Base
{
    public function up()
    {
      Doctrine_Manager::getInstance()->connection()->execute("CREATE TABLE sf_combine (asset_key VARCHAR(40), files LONGTEXT NOT NULL, PRIMARY KEY(asset_key)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = INNODB;");
    }

    public function down()
    {
      $this->dropTable('sf_combine');
    }
}