<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddTableInterfaceLabel extends Doctrine_Migration_Base
{
    public function up()
    {
      Doctrine_Manager::getInstance()->getCurrentConnection()->execute("CREATE TABLE interface_label (id BIGINT AUTO_INCREMENT, user_id BIGINT, type BIGINT, singular VARCHAR(64), plural VARCHAR(64), INDEX user_id_idx (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = INNODB;");
      Doctrine_Manager::getInstance()->getCurrentConnection()->execute("ALTER TABLE interface_label ADD CONSTRAINT interface_label_user_id_sf_guard_user_id FOREIGN KEY (user_id) REFERENCES sf_guard_user(id) ON UPDATE CASCADE ON DELETE CASCADE;");
    }

    public function down()
    {
      $this->dropForeignKey('interface_label', 'interface_label_user_id_sf_guard_user_id');
      $this->dropTable('interface_label');
    }
}