<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MoveDecisionAndRoadmapToFolder extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->handleDecisions();
    $this->handleRoadmaps();
  }

  private function handleDecisions() {
    $default_folders = array();
    $conn = Doctrine_Manager::getInstance()->connection();
    $decisions = $conn->execute("SELECT id, user_id from `decision` WHERE folder_id is NULL")->fetchAll();

    foreach ($decisions as $decision) {
      if (!array_key_exists($decision['user_id'], $default_folders)) {
        $folder = $conn->execute("SELECT id from `folder` WHERE `user_id` = :user_id and `type` = '" . Folder::TYPE_PROJECT . "' and `deletable` = 0 LIMIT 1;", array(':user_id' => $decision['user_id']))->fetchAll();
        if (count($folder)) {
          $default_folders[$decision['user_id']] = $folder[0]['id'];
        }else{
          $folder = new Folder();
          $folder->setName('Default');
          $folder->setUserId($decision['user_id']);
          $folder->setDeletable(0);
          $folder->setType(Folder::TYPE_PROJECT);
          $folder->save();

          $default_folders[$decision['user_id']] = $folder->getId();
        }
      }

      $conn->execute("UPDATE `decision` SET `folder_id` = :folder_id WHERE id = :id", array(':folder_id' => $default_folders[$decision['user_id']], ':id' => $decision['id']));
    }
  }

  public function handleRoadmaps() {
    $default_folders = array();
    $conn = Doctrine_Manager::getInstance()->connection();
    $roadmaps = $conn->execute("SELECT id, user_id from `roadmap` WHERE folder_id is NULL")->fetchAll();

    foreach ($roadmaps as $roadmap) {
      if (!array_key_exists($roadmap['user_id'], $default_folders)) {
        $folder = $conn->execute("SELECT id from `folder` WHERE `user_id` = :user_id and `type` = '" . Folder::TYPE_ROADMAP . "' and `deletable` = 0 LIMIT 1;", array(':user_id' => $roadmap['user_id']))->fetchAll();
        if (count($folder)) {
          $default_folders[$roadmap['user_id']] = $folder[0]['id'];
        }else{
          $folder = new Folder();
          $folder->setName('Default');
          $folder->setUserId($roadmap['user_id']);
          $folder->setDeletable(0);
          $folder->setType(Folder::TYPE_ROADMAP);
          $folder->save();

          $default_folders[$roadmap['user_id']] = $folder->getId();
        }
      }

      $conn->execute("UPDATE `roadmap` SET `folder_id` = :folder_id WHERE id = :id", array(':folder_id' => $default_folders[$roadmap['user_id']], ':id' => $roadmap['id']));
    }
  }

  public function down()
  {

  }
}