<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddCustomFields extends Doctrine_Migration_Base
{
    public function up()
    {
      $this->addColumn('alternative', 'custom_fields', 'text');
    }

    public function down()
    {
      $this->removeColumn('alternative', 'custom_fields');
    }
}