<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ChangeMeasurementAddRelations extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->createForeignKey('alternative_measurement',
      'alternative_measurement_alternative_head_id_alternative_id',
      array(
        'name'         => 'alternative_measurement_alternative_head_id_alternative_id',
        'local'        => 'alternative_head_id',
        'foreign'      => 'id',
        'foreignTable' => 'alternative',
        'onUpdate'     => '',
        'onDelete'     => 'CASCADE',
      ));

    $this->createForeignKey('criterion_prioritization',
      'criterion_prioritization_criterion_head_id_criterion_id',
      array(
        'name'         => 'criterion_prioritization_criterion_head_id_criterion_id',
        'local'        => 'criterion_head_id',
        'foreign'      => 'id',
        'foreignTable' => 'criterion',
        'onUpdate'     => '',
        'onDelete'     => 'CASCADE',
      ));

    $this->createForeignKey('criterion_prioritization',
      'criterion_prioritization_criterion_tail_id_criterion_id',
      array(
        'name'         => 'criterion_prioritization_criterion_tail_id_criterion_id',
        'local'        => 'criterion_tail_id',
        'foreign'      => 'id',
        'foreignTable' => 'criterion',
        'onUpdate'     => '',
        'onDelete'     => 'CASCADE',
      ));
  }

  public function down()
  {
    $this->dropForeignKey('alternative_measurement', 'alternative_measurement_alternative_head_id_alternative_id');
    $this->dropForeignKey('criterion_prioritization', 'criterion_prioritization_criterion_head_id_criterion_id');
    $this->dropForeignKey('criterion_prioritization', 'criterion_prioritization_criterion_tail_id_criterion_id');

    $this->removeIndex('alternative_measurement', 'alternative_head_id',
      array(
        'fields' =>
        array(
          0 => 'alternative_head_id',
        ),
      ));

    $this->removeIndex('criterion_prioritization', 'criterion_head_id',
      array('fields' =>
        array(
          0 => 'criterion_head_id',
        ),
      ));

     $this->removeIndex('criterion_prioritization', 'criterion_tail_id',
      array('fields' =>
        array(
          0 => 'criterion_tail_id',
        ),
      ));
  }
}