<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UpdateableByDefault extends Doctrine_Migration_Base
{
    public function up()
    {
      $this->changeColumn('role', 'updateable', 'boolean', '1', array('default' => '1'));
    }

    public function down()
    {
      $this->changeColumn('role', 'updateable', 'boolean', '1', array('default' => null));
    }
}