<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version111 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('graph_changes', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'graph_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'number' => 
             array(
              'type' => 'decimal',
              'scale' => '1',
              'length' => '20',
             ),
             'criterion_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('graph_changes');
    }
}