<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version112 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('graph_changes', 'graph_changes_graph_id_graph_id', array(
             'name' => 'graph_changes_graph_id_graph_id',
             'local' => 'graph_id',
             'foreign' => 'id',
             'foreignTable' => 'graph',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('graph_changes', 'graph_changes_criterion_id_criterion_id', array(
             'name' => 'graph_changes_criterion_id_criterion_id',
             'local' => 'criterion_id',
             'foreign' => 'id',
             'foreignTable' => 'criterion',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('graph_changes', 'graph_changes_graph_id', array(
             'fields' => 
             array(
              0 => 'graph_id',
             ),
             ));
        $this->addIndex('graph_changes', 'graph_changes_criterion_id', array(
             'fields' => 
             array(
              0 => 'criterion_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('graph_changes', 'graph_changes_graph_id_graph_id');
        $this->dropForeignKey('graph_changes', 'graph_changes_criterion_id_criterion_id');
        $this->removeIndex('graph_changes', 'graph_changes_graph_id', array(
             'fields' => 
             array(
              0 => 'graph_id',
             ),
             ));
        $this->removeIndex('graph_changes', 'graph_changes_criterion_id', array(
             'fields' => 
             array(
              0 => 'criterion_id',
             ),
             ));
    }
}