<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version115 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('tag_release', 'tag_release_release_id_project_release_id', array(
             'name' => 'tag_release_release_id_project_release_id',
             'local' => 'release_id',
             'foreign' => 'id',
             'foreignTable' => 'project_release',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('tag_release', 'tag_release_tag_id_tag_id', array(
             'name' => 'tag_release_tag_id_tag_id',
             'local' => 'tag_id',
             'foreign' => 'id',
             'foreignTable' => 'tag',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('tag_release', 'tag_release_release_id', array(
             'fields' => 
             array(
              0 => 'release_id',
             ),
             ));
        $this->addIndex('tag_release', 'tag_release_tag_id', array(
             'fields' => 
             array(
              0 => 'tag_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('tag_release', 'tag_release_release_id_project_release_id');
        $this->dropForeignKey('tag_release', 'tag_release_tag_id_tag_id');
        $this->removeIndex('tag_release', 'tag_release_release_id', array(
             'fields' => 
             array(
              0 => 'release_id',
             ),
             ));
        $this->removeIndex('tag_release', 'tag_release_tag_id', array(
             'fields' => 
             array(
              0 => 'tag_id',
             ),
             ));
    }
}