<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ChangeCriterionMeasurementDefault extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->changeColumn('criterion', 'measurement', 'enum', '',
      array(
        'values'  =>
        array(
          0 => 'direct rating',
          1 => 'forced ranking',
          2 => 'five point scale',
          3 => 'ten point scale',
        ),
        'default' => 'five point scale',
      ));
  }

  public function down()
  {

  }
}