<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RoleUpdateableResponseMigration extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->addColumn('response', 'role_id', 'integer', '8', array());
    $this->addColumn('role', 'updateable', 'boolean', '25', array());
  }

  public function down()
  {
    $this->removeColumn('response', 'role_id');
    $this->removeColumn('role', 'updateable');
  }
}