<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RoleUpdateableResponseRelationMigration extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->createForeignKey('response', 'response_role_id_role_id',
      array(
        'name'         => 'response_role_id_role_id',
        'local'        => 'role_id',
        'foreign'      => 'id',
        'foreignTable' => 'role',
        'onUpdate'     => '',
        'onDelete'     => 'CASCADE',
      ));

    $this->addIndex('response', 'response_role_id',
      array(
        'fields' =>
        array(
          0 => 'role_id',
        ),
      ));
  }

  public function down()
  {
    $this->dropForeignKey('response', 'response_role_id_role_id');
    $this->removeIndex('response',
      'response_role_id',
      array(
        'fields' =>
        array(
          0 => 'role_id',
        ),
      ));
  }
}