<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RoleDisableViewAsMatrix extends Doctrine_Migration_Base
{
  public function up()
  {
    Doctrine_Query::create()
      ->from('Role')
      ->update()
      ->set('view_matrix', 0)
      ->execute();
  }

  public function down()
  {

  }
}