<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ChangeDefaultAccountMigration extends Doctrine_Migration_Base
{
  public function preUp()
  {
    Doctrine_Query::create()->update('sfGuardUser u')
      ->set('u.account_type', '"Free"')
      ->where('u.account_type = "Trial"')
      ->execute();
  }

  public function up()
  {
    $this->changeColumn('sf_guard_user',
      'account_type',
      'enum',
      '',
      array(
        'values'  =>
        array(
          0 => 'Trial',
          1 => 'Basic',
          2 => 'Enterprise',
          3 => 'Consultant',
          4 => 'Free',
        ),
        'default' => 'Free',
      ));
  }

  public function down()
  {

  }
}