<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReleaseMigration extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->createTable(
      'project_release',
      array(
        'id'           =>
        array(
          'type'          => 'integer',
          'length'        => '8',
          'autoincrement' => '1',
          'primary'       => '1',
        ),
        'decision_id'  =>
        array(
          'type'    => 'integer',
          'notnull' => '1',
          'length'  => '8',
        ),
        'criterion_id' =>
        array(
          'type'    => 'integer',
          'notnull' => '1',
          'length'  => '8',
        ),
        'name'         =>
        array(
          'type'   => 'string',
          'length' => '255',
        ),
        'value'        =>
        array(
          'type'    => 'decimal',
          'scale'   => '2',
          'length'  => '20',
          'default' => '0'
        ),
      ),
      array(
        'primary' =>
        array(
          0 => 'id',
        ),
        'collate' => 'utf8_general_ci',
        'charset' => 'utf8',
      )
    );
    $this->createTable(
      'project_release_alternative',
      array(
        'id'             =>
        array(
          'type'          => 'integer',
          'length'        => '8',
          'autoincrement' => '1',
          'primary'       => '1',
        ),
        'release_id'     =>
        array(
          'type'    => 'integer',
          'notnull' => '1',
          'length'  => '8',
        ),
        'alternative_id' =>
        array(
          'type'    => 'integer',
          'notnull' => '1',
          'length'  => '8',
        ),
        'value'          =>
        array(
          'type'   => 'decimal',
          'scale'  => '2',
          'length' => '20',
        ),
      ),
      array(
        'primary' =>
        array(
          0 => 'id',
        ),
        'collate' => 'utf8_general_ci',
        'charset' => 'utf8',
      )
    );
  }

  public function down()
  {
    $this->dropTable('project_release');
    $this->dropTable('project_release_alternative');
  }
}