<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReleaseRelationsMigration extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->createForeignKey(
      'project_release',
      'project_release_decision_id_decision_id',
      array(
        'name'         => 'project_release_decision_id_decision_id',
        'local'        => 'decision_id',
        'foreign'      => 'id',
        'foreignTable' => 'decision',
        'onUpdate'     => '',
        'onDelete'     => 'CASCADE',
      )
    );
    $this->createForeignKey(
      'project_release_alternative',
      'project_release_alternative_release_id_project_release_id',
      array(
        'name'         => 'project_release_alternative_release_id_project_release_id',
        'local'        => 'release_id',
        'foreign'      => 'id',
        'foreignTable' => 'project_release',
        'onUpdate'     => '',
        'onDelete'     => 'CASCADE',
      )
    );
    $this->createForeignKey(
      'project_release_alternative',
      'project_release_alternative_alternative_id_alternative_id',
      array(
        'name'         => 'project_release_alternative_alternative_id_alternative_id',
        'local'        => 'alternative_id',
        'foreign'      => 'id',
        'foreignTable' => 'alternative',
        'onUpdate'     => '',
        'onDelete'     => 'CASCADE',
      )
    );
    $this->createForeignKey(
      'project_release',
      'project_release_criterion_id_criterion_id',
      array(
        'name'         => 'project_release_criterion_id_criterion_id',
        'local'        => 'criterion_id',
        'foreign'      => 'id',
        'foreignTable' => 'criterion',
        'onUpdate'     => '',
        'onDelete'     => 'CASCADE',
      )
    );
    $this->addIndex(
      'project_release',
      'project_release_criterion_id',
      array(
        'fields' =>
        array(
          0 => 'criterion_id',
        ),
      )
    );
    $this->addIndex(
      'project_release',
      'project_release_decision_id',
      array(
        'fields' =>
        array(
          0 => 'decision_id',
        ),
      )
    );
    $this->addIndex(
      'project_release_alternative',
      'project_release_alternative_release_id',
      array(
        'fields' =>
        array(
          0 => 'release_id',
        ),
      )
    );
    $this->addIndex(
      'project_release_alternative',
      'project_release_alternative_alternative_id',
      array(
        'fields' =>
        array(
          0 => 'alternative_id',
        ),
      )
    );
  }

  public function down()
  {
    $this->dropForeignKey('project_release', 'project_release_decision_id_decision_id');
    $this->dropForeignKey('project_release_alternative', 'project_release_alternative_release_id_project_release_id');
    $this->dropForeignKey('project_release_alternative', 'project_release_alternative_alternative_id_alternative_id');
    $this->dropForeignKey('project_release', 'project_release_criterion_id_criterion_id');
    $this->removeIndex(
      'project_release',
      'project_release_criterion_id',
      array(
        'fields' =>
        array(
          0 => 'criterion_id',
        ),
      )
    );
    $this->removeIndex(
      'project_release',
      'project_release_decision_id',
      array(
        'fields' =>
        array(
          0 => 'decision_id',
        ),
      )
    );
    $this->removeIndex(
      'project_release_alternative',
      'project_release_alternative_release_id',
      array(
        'fields' =>
        array(
          0 => 'release_id',
        ),
      )
    );
    $this->removeIndex(
      'project_release_alternative',
      'project_release_alternative_alternative_id',
      array(
        'fields' =>
        array(
          0 => 'alternative_id',
        ),
      )
    );
  }
}