<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DecisionTemplateMigration extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->addColumn('decision', 'template_id', 'integer', '8', array('notnull' => false));
    $this->createTable(
      'criteria_template',
      array(
        'id'            =>
        array(
          'type'          => 'integer',
          'length'        => '8',
          'autoincrement' => '1',
          'primary'       => '1',
        ),
        'name'          =>
        array(
          'type'   => 'string',
          'length' => '255',
        ),
        'variable_type' =>
        array(
          'type'    => 'enum',
          'values'  =>
          array(
            0 => 'Benefit',
            1 => 'Cost',
            2 => 'Info',
          ),
          'default' => 'Benefit',
        ),
        'measurement'   =>
        array(
          'type'    => 'enum',
          'values'  =>
          array(
            0 => 'direct rating',
            1 => 'forced ranking',
            2 => 'five point scale',
            3 => 'ten point scale',
          ),
          'default' => 'five point scale',
        ),
        'template_id'   =>
        array(
          'type'    => 'integer',
          'notnull' => '1',
          'length'  => '8',
        ),
      ),
      array(
        'primary' =>
        array(
          0 => 'id',
        ),
        'collate' => 'utf8_general_ci',
        'charset' => 'utf8',
      )
    );
    $this->createTable(
      'role_template',
      array(
        'id'          =>
        array(
          'type'          => 'integer',
          'length'        => '8',
          'autoincrement' => '1',
          'primary'       => '1',
        ),
        'name'        =>
        array(
          'type'   => 'string',
          'length' => '255',
        ),
        'template_id' =>
        array(
          'type'    => 'integer',
          'notnull' => '1',
          'length'  => '8',
        ),
      ),
      array(
        'primary' =>
        array(
          0 => 'id',
        ),
        'collate' => 'utf8_general_ci',
        'charset' => 'utf8',
      )
    );
    $this->createTable(
      'type_template',
      array(
        'id'                       =>
        array(
          'type'          => 'integer',
          'length'        => '8',
          'autoincrement' => '1',
          'primary'       => '1',
        ),
        'name'                     =>
        array(
          'type'   => 'string',
          'length' => '255',
        ),
        'type_id'                  =>
        array(
          'type'    => 'integer',
          'notnull' => '1',
          'length'  => '8',
        ),
        'alternative_alias'        =>
        array(
          'type'   => 'string',
          'length' => '255',
        ),
        'alternative_plural_alias' =>
        array(
          'type'   => 'string',
          'length' => '255',
        ),
        'partitioner_alias'        =>
        array(
          'type'   => 'string',
          'length' => '64',
        ),
      ),
      array(
        'primary' =>
        array(
          0 => 'id',
        ),
        'collate' => 'utf8_general_ci',
        'charset' => 'utf8',
      )
    );
    $this->removeColumn('decision_type', 'alternative_alias');
    $this->removeColumn('decision_type', 'alternative_plural_alias');
  }

  public function down()
  {
    $this->dropTable('criteria_template');
    $this->dropTable('role_template');
    $this->dropTable('type_template');
    $this->addColumn('decision_type', 'alternative_alias', 'string', '255', array());
    $this->addColumn('decision_type', 'alternative_plural_alias', 'string', '255', array());
    $this->removeColumn('decision', 'template_id');
  }
}