<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DecisionTemplateRelationsMigration extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->createForeignKey(
      'criteria_template',
      'criteria_template_template_id_type_template_id',
      array(
        'name'         => 'criteria_template_template_id_type_template_id',
        'local'        => 'template_id',
        'foreign'      => 'id',
        'foreignTable' => 'type_template',
        'onUpdate'     => '',
        'onDelete'     => 'CASCADE',
      )
    );
    $this->createForeignKey(
      'role_template',
      'role_template_template_id_type_template_id',
      array(
        'name'         => 'role_template_template_id_type_template_id',
        'local'        => 'template_id',
        'foreign'      => 'id',
        'foreignTable' => 'type_template',
        'onUpdate'     => '',
        'onDelete'     => 'CASCADE',
      )
    );
    $this->createForeignKey(
      'type_template',
      'type_template_type_id_decision_type_id',
      array(
        'name'         => 'type_template_type_id_decision_type_id',
        'local'        => 'type_id',
        'foreign'      => 'id',
        'foreignTable' => 'decision_type',
        'onUpdate'     => '',
        'onDelete'     => 'CASCADE',
      )
    );
    $this->createForeignKey(
      'decision',
      'decision_template_id_type_template_id',
      array(
        'name'         => 'decision_template_id_type_template_id',
        'local'        => 'template_id',
        'foreign'      => 'id',
        'foreignTable' => 'type_template',
        'onUpdate'     => '',
        'onDelete'     => 'CASCADE',
      )
    );
    $this->addIndex(
      'decision',
      'decision_template_id',
      array(
        'fields' =>
        array(
          0 => 'template_id',
        ),
      )
    );
    $this->addIndex(
      'criteria_template',
      'criteria_template_template_id',
      array(
        'fields' =>
        array(
          0 => 'template_id',
        ),
      )
    );
    $this->addIndex(
      'role_template',
      'role_template_template_id',
      array(
        'fields' =>
        array(
          0 => 'template_id',
        ),
      )
    );
    $this->addIndex(
      'type_template',
      'type_template_type_id',
      array(
        'fields' =>
        array(
          0 => 'type_id',
        ),
      )
    );
  }

  public function down()
  {
    $this->dropForeignKey('criteria_template', 'criteria_template_template_id_type_template_id');
    $this->dropForeignKey('role_template', 'role_template_template_id_type_template_id');
    $this->dropForeignKey('type_template', 'type_template_type_id_decision_type_id');
    $this->dropForeignKey('decision', 'decision_template_id_type_template_id');
    $this->removeIndex(
      'decision',
      'decision_template_id',
      array(
        'fields' =>
        array(
          0 => 'template_id',
        ),
      )
    );
    $this->removeIndex(
      'criteria_template',
      'criteria_template_template_id',
      array(
        'fields' =>
        array(
          0 => 'template_id',
        ),
      )
    );
    $this->removeIndex(
      'role_template',
      'role_template_template_id',
      array(
        'fields' =>
        array(
          0 => 'template_id',
        ),
      )
    );
    $this->removeIndex(
      'type_template',
      'type_template_type_id',
      array(
        'fields' =>
        array(
          0 => 'type_id',
        ),
      )
    );
  }
}