<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlternativeUploadedFileMigration extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->createTable(
      'alternative_uploaded_file',
      array(
        'alternative_id'   =>
        array(
          'type'    => 'integer',
          'primary' => '1',
          'length'  => '8',
        ),
        'uploaded_file_id' =>
        array(
          'type'    => 'integer',
          'primary' => '1',
          'length'  => '8',
        ),
      ),
      array(
        'primary' =>
        array(
          0 => 'alternative_id',
          1 => 'uploaded_file_id',
        ),
        'collate' => 'utf8_general_ci',
        'charset' => 'utf8',
      )
    );
    $this->addColumn(
      'alternative',
      'link',
      'string',
      '255',
      array()
    );
  }

  public function down()
  {
    $this->dropTable('alternative_uploaded_file');
    $this->removeColumn('alternative', 'link');
  }
}