<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlternativeUploadedFileRelationsMigration extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->createForeignKey(
      'alternative_uploaded_file',
      'alternative_uploaded_file_alternative_id_alternative_id',
      array(
        'name'         => 'alternative_uploaded_file_alternative_id_alternative_id',
        'local'        => 'alternative_id',
        'foreign'      => 'id',
        'foreignTable' => 'alternative',
        'onUpdate'     => '',
        'onDelete'     => 'CASCADE',
      )
    );
    $this->createForeignKey(
      'alternative_uploaded_file',
      'alternative_uploaded_file_uploaded_file_id_uploaded_file_id',
      array(
        'name'         => 'alternative_uploaded_file_uploaded_file_id_uploaded_file_id',
        'local'        => 'uploaded_file_id',
        'foreign'      => 'id',
        'foreignTable' => 'uploaded_file',
        'onUpdate'     => '',
        'onDelete'     => 'CASCADE',
      )
    );
    $this->addIndex(
      'alternative_uploaded_file',
      'alternative_id',
      array(
        'fields' =>
        array(
          0 => 'alternative_id',
        ),
      )
    );
    $this->addIndex(
      'alternative_uploaded_file',
      'uploaded_file_id',
      array(
        'fields' =>
        array(
          0 => 'uploaded_file_id',
        ),
      )
    );
  }

  public function down()
  {
    $this->dropForeignKey('alternative_uploaded_file', 'alternative_uploaded_file_alternative_id_alternative_id');
    $this->dropForeignKey('alternative_uploaded_file', 'alternative_uploaded_file_uploaded_file_id_uploaded_file_id');
    $this->removeIndex(
      'alternative_uploaded_file',
      'alternative_uploaded_file_alternative_id',
      array(
        'fields' =>
        array(
          0 => 'alternative_id',
        ),
      )
    );
    $this->removeIndex(
      'alternative_uploaded_file',
      'alternative_uploaded_file_uploaded_file_id',
      array(
        'fields' =>
        array(
          0 => 'uploaded_file_id',
        ),
      )
    );
  }
}