<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CriterionCommentMeasurementMigration extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->changeColumn('criterion', 'measurement', 'enum', '',
      array(
        'values'  =>
        array(
          0 => 'direct rating',
          1 => 'forced ranking',
          2 => 'five point scale',
          3 => 'ten point scale',
          4 => 'comment'
        ),
        'default' => 'five point scale',
      )
    );

    $this->changeColumn('alternative_measurement', 'rating_method', 'enum', '', array(
        'values'  =>
        array(
          0 => 'direct rating',
          1 => 'forced ranking',
          2 => 'five point scale',
          3 => 'ten point scale',
          4 => 'comment',
        ),
        'notnull' => '1',
      )
    );

    $this->changeColumn('alternative_measurement', 'score', 'string', '', array());
  }

  public function down()
  {
  }
}