<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RoleAnonymousMigration extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->addColumn('role', 'anonymous', 'boolean', '25', array());
  }

  public function down()
  {
    $this->removeColumn('role', 'anonymous');
  }
}