<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AnalyzeFiltersMigration extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->createTable('logical_filter', array(
      'id' =>
      array(
        'type' => 'integer',
        'length' => '8',
        'autoincrement' => '1',
        'primary' => '1',
      ),
      'decision_id' =>
      array(
        'type' => 'integer',
        'notnull' => '1',
        'length' => '8',
      ),
      'criterion_id' =>
      array(
        'type' => 'integer',
        'notnull' => '1',
        'length' => '8',
      ),
      'logical_operator' =>
      array(
        'type' => 'enum',
        'values' =>
        array(
          0 => '>',
          1 => '<',
          2 => '=',
        ),
        'notnull' => '1',
        'length' => '',
      ),
      'value' =>
      array(
        'type' => 'integer',
        'length' => '8',
      ),
    ), array(
      'primary' =>
      array(
        0 => 'id',
      ),
      'collate' => 'utf8_general_ci',
      'charset' => 'utf8',
    ));
    $this->createTable('role_filter', array(
      'id' =>
      array(
        'type' => 'integer',
        'length' => '8',
        'autoincrement' => '1',
        'primary' => '1',
      ),
      'decision_id' =>
      array(
        'type' => 'integer',
        'notnull' => '1',
        'length' => '8',
      ),
      'role_id' =>
      array(
        'type' => 'integer',
        'notnull' => '1',
        'length' => '8',
      ),
    ), array(
      'indexes' =>
      array(
        'role_filter_decsion_idx' =>
        array(
          'fields' =>
          array(
            0 => 'role_id',
            1 => 'decision_id',
          ),
          'type' => 'unique',
        ),
      ),
      'primary' =>
      array(
        0 => 'id',
      ),
      'collate' => 'utf8_general_ci',
      'charset' => 'utf8',
    ));
  }

  public function down()
  {
    $this->dropTable('logical_filter');
    $this->dropTable('role_filter');
  }
}