<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PermissionDecisionManagementMigration extends Doctrine_Migration_Base
{
  public function up()
  {
    $permission = new sfGuardPermission();
    $permission->name = 'decision_management';
    $permission->description = 'Decision management';
    $permission->save();
  }

  public function down()
  {
    Doctrine::getTable('sfGuardPermission')->findOneByName('decision_management')->delete();
  }
}