<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AnalyzeFiltersRelationsMigration extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->createForeignKey('logical_filter', 'logical_filter_decision_id_decision_id', array(
      'name' => 'logical_filter_decision_id_decision_id',
      'local' => 'decision_id',
      'foreign' => 'id',
      'foreignTable' => 'decision',
      'onUpdate' => '',
      'onDelete' => 'CASCADE',
    ));
    $this->createForeignKey('logical_filter', 'logical_filter_criterion_id_criterion_id', array(
      'name' => 'logical_filter_criterion_id_criterion_id',
      'local' => 'criterion_id',
      'foreign' => 'id',
      'foreignTable' => 'criterion',
      'onUpdate' => '',
      'onDelete' => 'CASCADE',
    ));
    $this->createForeignKey('role_filter', 'role_filter_decision_id_decision_id', array(
      'name' => 'role_filter_decision_id_decision_id',
      'local' => 'decision_id',
      'foreign' => 'id',
      'foreignTable' => 'decision',
      'onUpdate' => '',
      'onDelete' => 'CASCADE',
    ));
    $this->createForeignKey('role_filter', 'role_filter_role_id_role_id', array(
      'name' => 'role_filter_role_id_role_id',
      'local' => 'role_id',
      'foreign' => 'id',
      'foreignTable' => 'role',
      'onUpdate' => '',
      'onDelete' => 'CASCADE',
    ));
    $this->addIndex('logical_filter', 'logical_filter_decision_id', array(
      'fields' =>
      array(
        0 => 'decision_id',
      ),
    ));
    $this->addIndex('logical_filter', 'logical_filter_criterion_id', array(
      'fields' =>
      array(
        0 => 'criterion_id',
      ),
    ));
    $this->addIndex('role_filter', 'role_filter_decision_id', array(
      'fields' =>
      array(
        0 => 'decision_id',
      ),
    ));
    $this->addIndex('role_filter', 'role_filter_role_id', array(
      'fields' =>
      array(
        0 => 'role_id',
      ),
    ));
  }

  public function down()
  {
    $this->dropForeignKey('logical_filter', 'logical_filter_decision_id_decision_id');
    $this->dropForeignKey('logical_filter', 'logical_filter_criterion_id_criterion_id');
    $this->dropForeignKey('role_filter', 'role_filter_decision_id_decision_id');
    $this->dropForeignKey('role_filter', 'role_filter_role_id_role_id');
    $this->removeIndex('logical_filter', 'logical_filter_decision_id', array(
      'fields' =>
      array(
        0 => 'decision_id',
      ),
    ));
    $this->removeIndex('logical_filter', 'logical_filter_criterion_id', array(
      'fields' =>
      array(
        0 => 'criterion_id',
      ),
    ));
    $this->removeIndex('role_filter', 'role_filter_decision_id', array(
      'fields' =>
      array(
        0 => 'decision_id',
      ),
    ));
    $this->removeIndex('role_filter', 'role_filter_role_id', array(
      'fields' =>
      array(
        0 => 'role_id',
      ),
    ));
  }
}