<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DirectFloatMigration extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->changeColumn('alternative_measurement', 'rating_method', 'enum', '', array(
      'values' =>
      array(
        0 => 'direct rating',
        1 => 'direct float',
        2 => 'forced ranking',
        3 => 'five point scale',
        4 => 'ten point scale',
        5 => 'comment',
      ),
      'notnull' => '1',
    ));
    $this->changeColumn('criteria_template', 'measurement', 'enum', '', array(
      'values' =>
      array(
        0 => 'direct rating',
        1 => 'direct float',
        2 => 'forced ranking',
        3 => 'five point scale',
        4 => 'ten point scale',
      ),
      'default' => 'five point scale',
    ));
    $this->changeColumn('criterion', 'measurement', 'enum', '', array(
      'values' =>
      array(
        0 => 'direct rating',
        1 => 'direct float',
        2 => 'forced ranking',
        3 => 'five point scale',
        4 => 'ten point scale',
        5 => 'comment',
      ),
      'default' => 'five point scale',
    ));
    $this->changeColumn('criterion_prioritization', 'rating_method', 'enum', '', array(
      'values' =>
      array(
        0 => 'direct rating',
        1 => 'direct float',
        2 => 'forced ranking',
        3 => 'five point scale',
        4 => 'ten point scale',
        5 => 'pairwise comparison',
      ),
      'notnull' => '1',
    ));
  }

  public function down()
  {

  }
}