<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlternativeLinkRelationsMigration extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->createForeignKey(
      'alternative_link',
      'alternative_link_alternative_id_alternative_id',
      array(
        'name'         => 'alternative_link_alternative_id_alternative_id',
        'local'        => 'alternative_id',
        'foreign'      => 'id',
        'foreignTable' => 'alternative',
        'onUpdate'     => '',
        'onDelete'     => 'CASCADE',
      )
    );
    $this->addIndex(
      'alternative_link',
      'alternative_id',
      array(
        'fields' =>
        array(
          0 => 'alternative_id',
        ),
      )
    );
  }

  public function down()
  {
    $this->dropForeignKey('alternative_link', 'alternative_link_alternative_id_alternative_id');
    $this->removeIndex(
      'alternative_link',
      'alternative_id',
      array(
        'fields' =>
        array(
          0 => 'alternative_id',
        ),
      )
    );
  }
}