<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserDecisionTypeMigration extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->createTable(
      'user_decision_type',
      array(
        'id'      =>
        array(
          'type'          => 'integer',
          'length'        => '8',
          'autoincrement' => '1',
          'primary'       => '1',
        ),
        'user_id' =>
        array(
          'type'   => 'integer',
          'length' => '8',
        ),
        'type_id' =>
        array(
          'type'   => 'integer',
          'length' => '8',
        ),
      ),
      array(
        'primary' =>
        array(
          0 => 'id',
        ),
        'collate' => 'utf8_general_ci',
        'charset' => 'utf8',
      )
    );
  }

  public function down()
  {
    $this->dropTable('user_decision_type');
  }
}