<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RolePrioritizationMethodMigration extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->addColumn('role', 'prioritization_method', 'enum', '',
      array(
        'values'  =>
          array(
            0 => 'forced ranking',
            1 => 'five point scale',
            2 => 'ten point scale',
            3 => 'pairwise comparison',
          ),
        'default' => 'five point scale',
      )
    );
  }

  public function postUp()
  {
    $conn = Doctrine_Manager::connection();
    $conn->exec('
      UPDATE role r LEFT JOIN decision d ON r.decision_id = d.id
      SET r.prioritization_method = d.prioritization_method
      WHERE r.prioritize = 1
       ');
  }

  public function down()
  {
  }
}