<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DecisionPrioritizationMethodMigration extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('decision', 'prioritization_method');
    }

    public function down()
    {
    }
}