<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RoleShowPreliminaryChartMigration extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->addColumn('role', 'show_criteria_weights', 'boolean', '25', array());
    $this->addColumn('role', 'show_alternatives_score', 'boolean', '25', array());
  }

  public function down()
  {
    $this->removeColumn('role', 'show_criteria_weights');
    $this->removeColumn('role', 'show_alternatives_score');
  }
}