<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CommentMigration extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->createTable(
      'comment',
      array(
        'id'             =>
          array(
            'type'          => 'integer',
            'length'        => '8',
            'autoincrement' => '1',
            'primary'       => '1',
          ),
        'decision_id'    =>
          array(
            'type'    => 'integer',
            'notnull' => '1',
            'length'  => '8',
          ),
        'alternative_id' =>
          array(
            'type'    => 'integer',
            'notnull' => false,
            'length'  => '8',
          ),
        'criterion_id'   =>
          array(
            'type'    => 'integer',
            'notnull' => '1',
            'length'  => '8',
          ),
        'text'           =>
          array(
            'type'   => 'string',
            'length' => '',
          ),
        'email'          =>
          array(
            'type'   => 'string',
            'length' => '255',
          ),
        'user_id'        =>
          array(
            'type'   => 'integer',
            'length' => '8',
          ),
      ),
      array(
        'primary' =>
          array(
            0 => 'id',
          ),
        'collate' => 'utf8_general_ci',
        'charset' => 'utf8',
      )
    );
  }

  public function down()
  {
    $this->dropTable('comment');
  }
}