<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CommentRelationsMigration extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->createForeignKey(
      'comment',
      'comment_decision_id_decision_id',
      array(
        'name'         => 'comment_decision_id_decision_id',
        'local'        => 'decision_id',
        'foreign'      => 'id',
        'foreignTable' => 'decision',
        'onUpdate'     => '',
        'onDelete'     => 'CASCADE',
      )
    );
    $this->createForeignKey(
      'comment',
      'comment_criterion_id_criterion_id',
      array(
        'name'         => 'comment_criterion_id_criterion_id',
        'local'        => 'criterion_id',
        'foreign'      => 'id',
        'foreignTable' => 'criterion',
        'onUpdate'     => '',
        'onDelete'     => 'CASCADE',
      )
    );
    $this->createForeignKey(
      'comment',
      'comment_alternative_id_alternative_id',
      array(
        'name'         => 'comment_alternative_id_alternative_id',
        'local'        => 'alternative_id',
        'foreign'      => 'id',
        'foreignTable' => 'alternative',
        'onUpdate'     => '',
        'onDelete'     => 'CASCADE',
      )
    );
    $this->createForeignKey(
      'comment',
      'comment_user_id_sf_guard_user_id',
      array(
        'name'         => 'comment_user_id_sf_guard_user_id',
        'local'        => 'user_id',
        'foreign'      => 'id',
        'foreignTable' => 'sf_guard_user',
        'onUpdate'     => '',
        'onDelete'     => 'CASCADE',
      )
    );
    $this->addIndex(
      'comment',
      'comment_decision_id',
      array(
        'fields' =>
          array(
            0 => 'decision_id',
          ),
      )
    );
    $this->addIndex(
      'comment',
      'comment_criterion_id',
      array(
        'fields' =>
          array(
            0 => 'criterion_id',
          ),
      )
    );
    $this->addIndex(
      'comment',
      'comment_alternative_id',
      array(
        'fields' =>
          array(
            0 => 'alternative_id',
          ),
      )
    );
    $this->addIndex(
      'comment',
      'comment_user_id',
      array(
        'fields' =>
          array(
            0 => 'user_id',
          ),
      )
    );
  }

  public function down()
  {
    $this->dropForeignKey('comment', 'comment_decision_id_decision_id');
    $this->dropForeignKey('comment', 'comment_criterion_id_criterion_id');
    $this->dropForeignKey('comment', 'comment_alternative_id_alternative_id');
    $this->dropForeignKey('comment', 'comment_user_id_sf_guard_user_id');
    $this->removeIndex('comment', 'comment_decision_id',
      array(
        'fields' =>
          array(
            0 => 'decision_id',
          ),
      )
    );
    $this->removeIndex('comment', 'comment_criterion_id',
      array(
        'fields' =>
          array(
            0 => 'criterion_id',
          ),
      )
    );
    $this->removeIndex('comment', 'comment_alternative_id',
      array(
        'fields' =>
          array(
            0 => 'alternative_id',
          ),
      )
    );
    $this->removeIndex('comment', 'comment_user_id',
      array(
        'fields' =>
          array(
            0 => 'user_id',
          ),
      )
    );
  }
}