<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DecisionRemoveProblemMigration extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->removeColumn('decision', 'problem');
  }

  public function down()
  {
    $this->addColumn('decision', 'problem', 'string', '', array());
  }
}