<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TimestampableBehaviourMigration extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->addColumn(
      'alternative',
      'created_at',
      'timestamp',
      '25',
      array(
        'notnull' => '1',
      )
    );
    $this->addColumn(
      'alternative',
      'updated_at',
      'timestamp',
      '25',
      array(
        'notnull' => '1',
      )
    );
    $this->addColumn(
      'comment',
      'created_at',
      'timestamp',
      '25',
      array(
        'notnull' => '1',
      )
    );
    $this->addColumn(
      'comment',
      'updated_at',
      'timestamp',
      '25',
      array(
        'notnull' => '1',
      )
    );
    $this->addColumn(
      'criterion',
      'created_at',
      'timestamp',
      '25',
      array(
        'notnull' => '1',
      )
    );
    $this->addColumn(
      'criterion',
      'updated_at',
      'timestamp',
      '25',
      array(
        'notnull' => '1',
      )
    );
    $this->addColumn(
      'decision',
      'created_at',
      'timestamp',
      '25',
      array(
        'notnull' => '1',
      )
    );
    $this->addColumn(
      'decision',
      'updated_at',
      'timestamp',
      '25',
      array(
        'notnull' => '1',
      )
    );
    $this->addColumn(
      'role',
      'created_at',
      'timestamp',
      '25',
      array(
        'notnull' => '1',
      )
    );
    $this->addColumn(
      'role',
      'updated_at',
      'timestamp',
      '25',
      array(
        'notnull' => '1',
      )
    );
  }

  public function down()
  {
    $this->removeColumn('alternative', 'created_at');
    $this->removeColumn('alternative', 'updated_at');
    $this->removeColumn('comment', 'created_at');
    $this->removeColumn('comment', 'updated_at');
    $this->removeColumn('criterion', 'created_at');
    $this->removeColumn('criterion', 'updated_at');
    $this->removeColumn('decision', 'created_at');
    $this->removeColumn('decision', 'updated_at');
    $this->removeColumn('role', 'created_at');
    $this->removeColumn('role', 'updated_at');
  }
}