<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AnalyzeCollapseMigration extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->createTable(
      'analyze_collapse',
      array(
        'id'                   =>
          array(
            'type'          => 'integer',
            'length'        => '8',
            'autoincrement' => '1',
            'primary'       => '1',
          ),
        'decision_id'          =>
          array(
            'type'    => 'integer',
            'notnull' => '1',
            'length'  => '8',
          ),
        'filter'               =>
          array(
            'type'    => 'boolean',
            'default' => '1',
            'length'  => '25',
          ),
        'logic_filter'         =>
          array(
            'type'    => 'boolean',
            'default' => '0',
            'length'  => '25',
          ),
        'role'                 =>
          array(
            'type'    => 'boolean',
            'default' => '0',
            'length'  => '25',
          ),
        'criteria_weights'     =>
          array(
            'type'    => 'boolean',
            'default' => '1',
            'length'  => '25',
          ),
        'bar_chart'            =>
          array(
            'type'    => 'boolean',
            'default' => '0',
            'length'  => '25',
          ),
        'alternative_score'    =>
          array(
            'type'    => 'boolean',
            'default' => '0',
            'length'  => '25',
          ),
        'stacked_bar'          =>
          array(
            'type'    => 'boolean',
            'default' => '0',
            'length'  => '25',
          ),
        'graphs'               =>
          array(
            'type'    => 'boolean',
            'default' => '0',
            'length'  => '25',
          ),
        'xy_plot'              =>
          array(
            'type'    => 'boolean',
            'default' => '0',
            'length'  => '25',
          ),
        'bubble_plot'          =>
          array(
            'type'    => 'boolean',
            'default' => '0',
            'length'  => '25',
          ),
        'cumulative_gain'      =>
          array(
            'type'    => 'boolean',
            'default' => '0',
            'length'  => '25',
          ),
        'cost_allocation'      =>
          array(
            'type'    => 'boolean',
            'default' => '1',
            'length'  => '25',
          ),
        'budget_allocation'    =>
          array(
            'type'    => 'boolean',
            'default' => '0',
            'length'  => '25',
          ),
        'partitions'           =>
          array(
            'type'    => 'boolean',
            'default' => '1',
            'length'  => '25',
          ),
        'partition_allocation' =>
          array(
            'type'    => 'boolean',
            'default' => '0',
            'length'  => '25',
          ),
        'comments' =>
          array(
            'type'    => 'boolean',
            'default' => '0',
            'length'  => '25',
          ),
      ),
      array(
        'primary' =>
          array(
            0 => 'id',
          ),
        'collate' => 'utf8_general_ci',
        'charset' => 'utf8',
      )
    );
  }

  public function down()
  {
    $this->dropTable('analyze_collapse');
  }
}