<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DomainMigration extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->createTable(
      'domain',
      array(
        'id'   =>
          array(
            'type'          => 'integer',
            'length'        => '8',
            'autoincrement' => '1',
            'primary'       => '1',
          ),
        'name' =>
          array(
            'type'    => 'string',
            'notnull' => '1',
            'length'  => '128',
          ),
      ),
      array(
        'primary' =>
          array(
            0 => 'id',
          ),
        'collate' => 'utf8_general_ci',
        'charset' => 'utf8',
      )
    );
  }

  public function down()
  {
    $this->dropTable('domain');
  }
}