<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AnalyzeCollapseChangeMigration extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->changeColumn('analyze_collapse', 'criteria_weights', 'boolean', '25', array('default' => '0'));
  }

  public function down()
  {
  }
}