<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DecisionUserMigration extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->addColumn('decision', 'user_id', 'integer', '8', array());
  }

  public function down()
  {
    $this->removeColumn('decision', 'user_id');
  }
}