<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserAccountTypeMigration extends Doctrine_Migration_Base
{
  public function preUp()
  {
    Doctrine::getTable('sfGuardUser')->createQuery('u')
      ->update()
      ->set('u.account_type', '"Trial"')
      ->where('u.account_type = "Free"')
      ->execute();
  }

  public function up()
  {
    $this->changeColumn('sf_guard_user', 'account_type', 'enum', '',
      array(
        'values'  =>
          array(
            0 => 'Trial',
            1 => 'Basic',
            2 => 'Pro',
            3 => 'Enterprise',
          ),
        'default' => 'Trial',
      )
    );
  }

  public function down()
  {
  }
}