<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PaymentTransactionMigration extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->createTable('payment_transaction',
      array(
        'id'                  =>
          array(
            'type'          => 'integer',
            'length'        => '8',
            'autoincrement' => '1',
            'primary'       => '1',
          ),
        'user_id'             =>
          array(
            'type'   => 'integer',
            'length' => '8',
          ),
        'refnumber'           =>
          array(
            'type'   => 'string',
            'length' => '20',
          ),
        'status_code'         =>
          array(
            'type'   => 'string',
            'length' => '20',
          ),
        'is_payed'            =>
          array(
            'type'    => 'boolean',
            'default' => '0',
            'length'  => '25',
          ),
        'date_payed'          =>
          array(
            'type'   => 'timestamp',
            'length' => '',
          ),
        'stamp'               =>
          array(
            'type'   => 'string',
            'length' => '20',
          ),
        'amount'              =>
          array(
            'type'    => 'float',
            'default' => '0',
            'length'  => '',
          ),
        'type'                =>
          array(
            'type' => 'enum',
            'values' => array('basic', 'pro', 'enterprise')
          ),
        'created_at'          =>
          array(
            'notnull' => '1',
            'type'    => 'timestamp',
            'length'  => '25',
          ),
        'updated_at'          =>
          array(
            'notnull' => '1',
            'type'    => 'timestamp',
            'length'  => '25',
          ),
      ),
      array(
        'primary' =>
          array(
            0 => 'id',
          ),
        'collate' => 'utf8_general_ci',
        'charset' => 'utf8',
      )
    );
  }

  public function down()
  {
    $this->dropTable('payment_transaction');
  }
}