<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PaymentTransactionRelationMigration extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->createForeignKey('payment_transaction', 'payment_transaction_user_id_sf_guard_user_id',
      array(
        'name'         => 'payment_transaction_user_id_sf_guard_user_id',
        'local'        => 'user_id',
        'foreign'      => 'id',
        'foreignTable' => 'sf_guard_user',
        'onUpdate'     => '',
        'onDelete'     => 'CASCADE',
      )
    );
    $this->addIndex('payment_transaction', 'user_id', array('fields' => array('user_id')));
  }

  public function down()
  {
    $this->dropForeignKey('payment_transaction', 'payment_transaction_user_id_sf_guard_user_id');
    $this->removeIndex('payment_transaction', 'user_id', array('fields' => array('user_id')));
  }
}