<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class team_memberMigration extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->createTable(
      'team_member',
      array(
        'id'         =>
          array(
            'type'          => 'integer',
            'length'        => '8',
            'autoincrement' => '1',
            'primary'       => '1',
          ),
        'manager_id' =>
          array(
            'type'    => 'integer',
            'notnull' => '1',
            'length'  => '8',
          ),
        'user_id'    =>
          array(
            'type'    => 'integer',
            'notnull' => '1',
            'length'  => '8',
          ),
      ),
      array(
        'primary' =>
          array(
            0 => 'id',
          ),
        'collate' => 'utf8_general_ci',
        'charset' => 'utf8',
      )
    );
  }

  public function down()
  {
    $this->dropTable('team_member');
  }
}