<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TeamMemberRelationMigration extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->createForeignKey('team_member', 'team_member_manager_id_sf_guard_user_id',
      array(
        'name'         => 'team_member_manager_id_sf_guard_user_id',
        'local'        => 'manager_id',
        'foreign'      => 'id',
        'foreignTable' => 'sf_guard_user',
        'onUpdate'     => '',
        'onDelete'     => 'CASCADE',
      )
    );
    $this->createForeignKey('team_member', 'team_member_user_id_sf_guard_user_id',
      array(
        'name'         => 'team_member_user_id_sf_guard_user_id',
        'local'        => 'user_id',
        'foreign'      => 'id',
        'foreignTable' => 'sf_guard_user',
        'onUpdate'     => '',
        'onDelete'     => 'CASCADE',
      )
    );
    $this->addIndex('team_member', 'manager_id',
      array(
        'fields' =>
          array(
            0 => 'manager_id',
          ),
      )
    );
    $this->addIndex('team_member', 'user_id',
      array(
        'fields' =>
          array(
            0 => 'user_id',
          ),
      )
    );
  }

  public function down()
  {
    $this->dropForeignKey('team_member', 'team_member_manager_id_sf_guard_user_id');
    $this->dropForeignKey('team_member', 'team_member_user_id_sf_guard_user_id');
    $this->removeIndex('team_member', 'manager_id',
      array(
        'fields' =>
          array(
            0 => 'manager_id',
          ),
      )
    );
    $this->removeIndex('team_member', 'user_id',
      array(
        'fields' =>
          array(
            0 => 'user_id',
          ),
      )
    );
  }
}