<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RoleContinueUrlMigration extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->addColumn('role', 'continue_url', 'string', '255', array());
  }

  public function down()
  {
    $this->removeColumn('role', 'continue_url');
  }
}