<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RoleShowCommentsMigration extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->addColumn('role', 'show_comments', 'boolean', '25', array());
  }

  public function down()
  {
    $this->removeColumn('role', 'show_comments');
  }
}