<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DecisionUserRelationMigration extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->createForeignKey('decision', 'decision_user_id_sf_guard_user_id',
      array(
        'name'         => 'decision_user_id_sf_guard_user_id',
        'local'        => 'user_id',
        'foreign'      => 'id',
        'foreignTable' => 'sf_guard_user',
        'onUpdate'     => '',
        'onDelete'     => 'CASCADE',
      )
    );
  }

  public function postUp()
  {
    foreach (Doctrine::getTable('Decision')->findAll() as $decision)
    {
      $decision->user_id = 1;
      $decision->save();
    }
  }

  public function down()
  {
    $this->dropForeignKey('decision', 'decision_user_id_sf_guard_user_id');
  }
}