<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserHeaderColorMigration extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->removeColumn('sf_guard_user', 'logo_disable');
    $this->addColumn('sf_guard_user', 'header_color', 'string', '24', array('default' => '#343537'));
  }

  public function down()
  {
    $this->addColumn('sf_guard_user', 'logo_disable', 'boolean', '25', array('default' => '0'));
    $this->removeColumn('sf_guard_user', 'header_color');
  }
}