<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DecisionFolderMigration extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->createTable('folder',
      array(
        'id'      =>
          array(
            'type'          => 'integer',
            'length'        => '8',
            'autoincrement' => '1',
            'primary'       => '1',
          ),
        'name'    =>
          array(
            'type'   => 'string',
            'length' => '255',
          ),
        'user_id' =>
          array(
            'type'   => 'integer',
            'length' => '8',
          ),
      ),
      array(
        'primary' =>
          array(
            0 => 'id',
          ),
        'collate' => 'utf8_general_ci',
        'charset' => 'utf8',
      )
    );
    $this->addColumn('decision', 'assigned_to', 'integer', '8', array());
    $this->addColumn('decision', 'folder_id', 'integer', '8', array());
  }

  public function down()
  {
    $this->dropTable('folder');
    $this->removeColumn('decision', 'folder_id');
    $this->removeColumn('decision', 'assigned_to');
  }
}