<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DecisionFolderRelationMigration extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->createForeignKey('decision', 'decision_folder_id_folder_id',
      array(
        'name'         => 'decision_folder_id_folder_id',
        'local'        => 'folder_id',
        'foreign'      => 'id',
        'foreignTable' => 'folder',
        'onUpdate'     => '',
        'onDelete'     => 'CASCADE',
      )
    );
    $this->createForeignKey('folder', 'folder_user_id_sf_guard_user_id',
      array(
        'name'         => 'folder_user_id_sf_guard_user_id',
        'local'        => 'user_id',
        'foreign'      => 'id',
        'foreignTable' => 'sf_guard_user',
        'onUpdate'     => '',
        'onDelete'     => 'CASCADE',
      )
    );
    $this->createForeignKey('decision', 'decision_assigned_to_sf_guard_user_id',
      array(
        'name'         => 'decision_assigned_to_sf_guard_user_id',
        'local'        => 'assigned_to',
        'foreign'      => 'id',
        'foreignTable' => 'sf_guard_user',
        'onUpdate'     => '',
        'onDelete'     => 'CASCADE',
      )
    );
    $this->addIndex('decision', 'assigned_to', array('fields' => array(0 => 'assigned_to')));
    $this->addIndex('decision', 'folder_id', array('fields' => array(0 => 'folder_id')));
    $this->addIndex('folder', 'user_id', array('fields' => array(0 => 'user_id')));
  }

  public function down()
  {
    $this->dropForeignKey('decision', 'decision_folder_id_folder_id');
    $this->dropForeignKey('folder', 'folder_user_id_sf_guard_user_id');
    $this->dropForeignKey('decision', 'decision_assigned_to_sf_guard_user_id');
    $this->removeIndex('decision', 'assigned_to', array('fields' => array(0 => 'assigned_to')));
    $this->removeIndex('decision', 'folder_id', array('fields' => array(0 => 'folder_id')));
    $this->removeIndex('folder', 'user_id', array('fields' => array(0 => 'user_id')));
  }
}