<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RoleCollectItems extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->addColumn('alternative', 'score', 'integer', '8', array());
    $this->addColumn('role', 'collect_items', 'boolean', '25', array());
    $this->addColumn('role', 'display_items', 'boolean', '25', array());
    $this->addColumn('role', 'allow_voting', 'boolean', '25', array());
  }

  public function down()
  {
    $this->removeColumn('role', 'collect_items');
    $this->removeColumn('role', 'display_items');
    $this->removeColumn('role', 'allow_voting');
    $this->removeColumn('alternative', 'score');
  }
}