<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RestoreDeletedRoleMigration extends Doctrine_Migration_Base
{
  public function up()
  {
    Doctrine_Core::loadData(sfConfig::get('sf_data_dir') . '/restore.yml', true);
  }

  public function down()
  {

  }
}