<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DashboardMigration extends Doctrine_Migration_Base
{
  public function up()
  {
    //$this->addColumn('role', 'dashboard', 'boolean', '25', array());
  }

  public function postUp()
  {
    $decisions = DecisionTable::getInstance()->createQuery('d')
      ->innerJoin('d.Roles r')
      ->where('r.dashboard = 0')
      ->execute();

    foreach ($decisions as $decision)
    {
      $decision->createDashboard();
    }
  }

  public function down()
  {
    $this->removeColumn('role', 'dashboard');
  }
}