<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WizardMigration extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->addColumn('sf_guard_user', 'wizard', 'boolean', '25', array('default' => '0'));
  }

  public function down()
  {
    $this->removeColumn('sf_guard_user', 'wizard');
  }
}