<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OAuthTokenMigration extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->createTable(
      'token',
      array(
        'id'             =>
          array(
            'type'          => 'integer',
            'primary'       => '1',
            'autoincrement' => '1',
            'length'        => '8',
          ),
        'name'           =>
          array(
            'type'   => 'string',
            'length' => '127',
          ),
        'token_key'      =>
          array(
            'type'   => 'clob',
            'length' => '',
          ),
        'token_secret'   =>
          array(
            'type'   => 'clob',
            'length' => '',
          ),
        'user_id'        =>
          array(
            'type'   => 'integer',
            'length' => '8',
          ),
        'expire'         =>
          array(
            'type'   => 'integer',
            'length' => '11',
          ),
        'params'         =>
          array(
            'type'   => 'clob',
            'length' => '',
          ),
        'identifier'     =>
          array(
            'type'   => 'string',
            'length' => '255',
          ),
        'status'         =>
          array(
            'type'   => 'string',
            'length' => '127',
          ),
        'o_auth_version' =>
          array(
            'type'   => 'integer',
            'length' => '2',
          ),
        'created_at'     =>
          array(
            'notnull' => '1',
            'type'    => 'timestamp',
            'length'  => '25',
          ),
        'updated_at'     =>
          array(
            'notnull' => '1',
            'type'    => 'timestamp',
            'length'  => '25',
          ),
      ),
      array(
        'primary' =>
          array(
            0 => 'id',
          ),
        'collate' => 'utf8_general_ci',
        'charset' => 'utf8',
      )
    );
  }

  public function down()
  {
    $this->dropTable('token');
  }
}