<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OAuthTokenRelationMigration extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->createForeignKey('token', 'token_user_id_sf_guard_user_id',
      array(
        'name'         => 'token_user_id_sf_guard_user_id',
        'local'        => 'user_id',
        'foreign'      => 'id',
        'foreignTable' => 'sf_guard_user',
        'onUpdate'     => '',
        'onDelete'     => 'CASCADE'
      )
    );
    $this->addIndex('token', 'token_user_id',
      array(
        'fields' =>
          array(
            0 => 'user_id',
          ),
      )
    );
  }

  public function postUp()
  {
    /** @var sfGuardUser[] $users */
    $users = Doctrine::getTable('sfGuardUser')->findAll();

    foreach ($users as $user)
    {
      $token = $user->generateToken();
      $token->save();
    }
  }

  public function down()
  {
    $this->dropForeignKey('token', 'token_user_id_sf_guard_user_id');
    $this->removeIndex('token', 'token_user_id',
      array(
        'fields' =>
          array(
            0 => 'user_id',
          ),
      )
    );
  }
}