<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddDeletableFieldInTableFolder extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->addColumn('folder', 'deletable', 'boolean', '25', array(
      'default' => '1',
    ));
  }

  public function down()
  {
    $this->removeColumn('folder', 'deletable');
  }
}