<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddTableLog extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->createTable('log', array(
      'id' =>
        array(
          'type' => 'integer',
          'length' => '8',
          'autoincrement' => '1',
          'primary' => '1',
        ),
      'user_id' =>
        array(
          'type' => 'integer',
          'length' => '11',
        ),
      'created_at' =>
        array(
          'notnull' => '1',
          'type'    => 'timestamp',
          'length'  => '25',
        ),
      'action' =>
        array(
          'type'    => 'enum',
          'values'  =>
            array(
              0   => 'login',
              1   => 'project_create',
              2   => 'folder_create',
              3   => 'item_create',
              4   => 'item_update',
              5   => 'criteria_create',
              6   => 'criteria_update',
              7   => 'survey_create',
              8   => 'survey_update',
              9   => 'survey_answered',
              10  => 'budget_create',
              11  => 'budget_update',
              12  => 'release_create',
              13  => 'release_update',
              14  => 'wall_update',
              15  => 'wall_visit',
            ),
          'default' => 'login',
        ),
      'information' =>
        array(
          'type'   => 'varchar',
          'length' => '2000',
        ),
    ), array(
      'primary' =>
        array(
          0 => 'id',
        ),
      'collate' => 'utf8_general_ci',
      'charset' => 'utf8',
    ));
  }

  public function down()
  {
    $this->dropTable('log');
  }
}