<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddTableTag extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->createTable('tag', array(
      'id' =>
        array(
          'type' => 'integer',
          'length' => '8',
          'autoincrement' => '1',
          'primary' => '1',
        ),
      'user_id' =>
        array(
          'type' => 'integer',
          'length' => '11',
          'notnull' => '1',
        ),
      'name' =>
        array(
          'type'   => 'string',
          'length' => '127',
          'notnull' => '1',
        )
    ), array(
      'primary' =>
        array(
          0 => 'id',
        ),
      'collate' => 'utf8_general_ci',
      'charset' => 'utf8',
    ));

    $this->createTable('tag_decision', array(
      'id' =>
        array(
          'type' => 'integer',
          'length' => '8',
          'autoincrement' => '1',
          'primary' => '1',
        ),
      'tag_id' =>
        array(
          'type' => 'integer',
          'length' => '11',
        ),
      'decision_id' =>
        array(
          'type' => 'integer',
          'length' => '11',
        )
    ), array(
      'primary' =>
        array(
          0 => 'id',
        ),
      'collate' => 'utf8_general_ci',
      'charset' => 'utf8',
    ));

    $this->createTable('tag_alternative', array(
      'id' =>
        array(
          'type' => 'integer',
          'length' => '8',
          'autoincrement' => '1',
          'primary' => '1',
        ),
      'tag_id' =>
        array(
          'type' => 'integer',
          'length' => '11',
        ),
      'alternative_id' =>
        array(
          'type' => 'integer',
          'length' => '11',
        )
    ), array(
      'primary' =>
        array(
          0 => 'id',
        ),
      'collate' => 'utf8_general_ci',
      'charset' => 'utf8',
    ));
  }

  public function down()
  {
    $this->dropTable('tag');
    $this->dropTable('tag_decision');
    $this->dropTable('tag_alternative');
  }
}