<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddTablePromoCode extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->createTable('promo_code', array(
      'id' =>
        array(
          'type' => 'integer',
          'length' => '8',
          'autoincrement' => '1',
          'primary' => '1',
        ),
      'code' =>
        array(
          'type'    => 'string',
          'notnull' => '1',
          'length'  => '128',
        ),
      'account_type' =>
        array(
          'type'    => 'enum',
          'values'  =>
            array(
              0   => 'Trial',
              1   => 'Basic',
              2   => 'Pro',
              3   => 'Enterprise'
            ),
          'default' => 'Trial',
        )
    ), array(
      'primary' =>
        array(
          0 => 'id',
        ),
      'collate' => 'utf8_general_ci',
      'charset' => 'utf8',
    ));
  }

  public function down()
  {
    $this->dropTable('promo_code');
  }
}