<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddTableStatusFilter extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->createTable('status_filter', array(
      'id' =>
        array(
          'type' => 'integer',
          'length' => '8',
          'autoincrement' => '1',
          'primary' => '1',
        ),
      'decision_id' =>
        array(
          'type' => 'integer',
          'notnull' => '1',
          'length' => '8',
        ),
      'status' =>
        array(
          'type'    => 'enum',
          'values'  =>
            array(
              0 => 'Draft',
              1 => 'Reviewed',
              2 => 'Planned',
              3 => 'Doing',
              4 => 'Finished',
              5 => 'Parked'
            ),
          'default' => 'Draft',
        ),
    ), array(
      'indexes' =>
        array(
          'status_filter_decsion_idx' =>
            array(
              'fields' =>
                array(
                  0 => 'decision_id'
                ),
              'type' => 'unique',
            ),
        ),
      'primary' =>
        array(
          0 => 'id',
        ),
      'collate' => 'utf8_general_ci',
      'charset' => 'utf8',
    ));

    $this->addColumn('analyze_collapse', 'status_filter', 'boolean', '25', array('default' => '0'));
  }

  public function down()
  {
    $this->dropTable('status_filter');
    $this->removeColumn('analyze_collapse', 'status_filter');
  }
}