<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddTableTagFilter extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->createTable('tag_filter', array(
      'id' =>
        array(
          'type' => 'integer',
          'length' => '8',
          'autoincrement' => '1',
          'primary' => '1',
        ),
      'decision_id' =>
        array(
          'type' => 'integer',
          'notnull' => '1',
          'length' => '8',
        ),
      'tag_id' =>
        array(
          'type' => 'integer',
          'notnull' => '1',
          'length' => '8',
        ),

    ), array(
      'indexes' =>
        array(
          'status_filter_decsion_idx' =>
            array(
              'fields' =>
                array(
                  0 => 'decision_id',
                  1 => 'tag_id'
                ),
              'type' => 'unique',
            ),
        ),
      'primary' =>
        array(
          0 => 'id',
        ),
      'collate' => 'utf8_general_ci',
      'charset' => 'utf8',
    ));

    $this->addColumn('analyze_collapse', 'tag_filter', 'boolean', '25', array('default' => '0'));
  }

  public function down()
  {
    $this->dropTable('tag_filter');
    $this->removeColumn('analyze_collapse', 'tag_filter');
  }
}