<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RefactorTemplates extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->addColumn('type_template', 'user_id', 'integer', '8');
  }

  public function down()
  {
    $this->removeColumn('type_template', 'user_id');
  }
}