<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ItemNameNotNull extends Doctrine_Migration_Base
{
  public function up()
  {
    Doctrine::getTable('Alternative')->createQuery('a')
      ->update()
      ->set('a.name', '"New item"')
      ->where('a.name = ""')
      ->execute();

    $this->changeColumn('alternative', 'name', 'varchar', '255',
      array(
        'notnull' => true,
        'default' => 'New item',
      )
    );

    Doctrine::getTable('Criterion')->createQuery('a')
      ->update()
      ->set('a.name', '"New criterion"')
      ->where('a.name = ""')
      ->execute();

    $this->changeColumn('criterion', 'name', 'varchar', '255',
      array(
        'notnull' => true,
        'default' => 'New criterion',
      )
    );

    Doctrine::getTable('Role')->createQuery('a')
      ->update()
      ->set('a.name', '"New role"')
      ->where('a.name = ""')
      ->execute();

    $this->changeColumn('role', 'name', 'varchar', '255',
      array(
        'notnull' => true,
        'default' => 'New role',
      )
    );
  }

  public function down()
  {
    $this->changeColumn('alternative', 'name', 'varchar', '255',
      array(
        'notnull' => false,
      )
    );

    $this->changeColumn('criterion', 'name', 'varchar', '255',
      array(
        'notnull' => true,
      )
    );

    $this->changeColumn('role', 'name', 'varchar', '255',
      array(
        'notnull' => true
      )
    );
  }
}