<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddUserTemplateForeignKey extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->createForeignKey('type_template', 'type_template_user_id_sf_guard_user_id',
      array(
        'name'         => 'type_template_user_id_sf_guard_user_id',
        'local'        => 'user_id',
        'foreign'      => 'id',
        'foreignTable' => 'sf_guard_user',
        'onUpdate'     => '',
        'onDelete'     => 'CASCADE',
      )
    );
  }

  public function down()
  {
    $this->dropForeignKey('type_template', 'type_template_user_id_sf_guard_user_id');
  }
}