<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddCreatedAndUpdatedByToAlternative extends Doctrine_Migration_Base
{
    public function up()
    {
      $this->addColumn('alternative', 'created_by', 'varchar', '255');
      $this->addColumn('alternative', 'updated_by', 'varchar', '255');

      $this->addColumn('wall_post', 'type', 'varchar', '20');
    }

    public function down()
    {
      $this->removeColumn('alternative', 'created_by');
      $this->removeColumn('alternative', 'updated_by');

      $this->removeColumn('wall_post', 'type');
    }
}