<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddScriptFields extends Doctrine_Migration_Base
{
    public function up()
    {
      $this->addColumn('scripts', 'frontend_top', 'varchar', '2000');
      $this->addColumn('scripts', 'frontend_bottom', 'varchar', '2000');
      $this->addColumn('scripts', 'backend_top', 'varchar', '2000');
      $this->addColumn('scripts', 'backend_bottom', 'varchar', '2000');
    }

    public function postUp(){
      Doctrine::getTable('Scripts')->createQuery('s')
        ->update()
        ->set('s.frontend_top', 'top')
        ->set('s.frontend_bottom', 'bottom')
        ->set('s.backend_top', 'top')
        ->set('s.backend_bottom', 'bottom')
        ->execute();

      Doctrine_Manager::getInstance()
        ->getCurrentConnection()->getDbh()
        ->query('ALTER TABLE `scripts` DROP `top`, DROP `bottom`;');
    }

    public function down()
    {
      $this->removeColumn('scripts', 'frontend_top');
      $this->removeColumn('scripts', 'frontend_bottom');

      $this->addColumn('scripts', 'top', 'varchar', '2000');
      $this->addColumn('scripts', 'bottom', 'varchar', '2000');
    }

    public function postDown(){
      Doctrine::getTable('Scripts')->createQuery('s')
        ->update()
        ->set('s.top', 'backend_top')
        ->set('s.bottom', 'backend_bottom')
        ->execute();

      Doctrine_Manager::getInstance()
        ->getCurrentConnection()->getDbh()
        ->query('ALTER TABLE `scripts` DROP `backend_top`, DROP `backend_bottom`;');
    }
}