<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddParamsToWallPost extends Doctrine_Migration_Base
{
    public function up()
    {
      $this->addColumn('wall_post', 'params', 'text');
    }

    public function down()
    {
      $this->removeColumn('wall_post', 'params');
    }
}