<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UpgradeAlternative extends Doctrine_Migration_Base
{
    public function up()
    {
      $this->addColumn('alternative', 'due_date', 'datetime');
      $this->addColumn('alternative', 'notify_date', 'datetime');
      $this->addColumn('alternative', 'external_id', 'varchar', '50');
      $this->addColumn('alternative', 'notes', 'text');
      $this->addColumn('alternative', 'assigned_to', 'integer', '8');
      $this->addColumn('alternative', 'work_progress', 'tinyint unsigned DEFAULT 0');
      $this->createForeignKey('alternative', 'alternative_assigned_to_sf_guard_user_id',
        array(
          'name'         => 'alternative_assigned_to_sf_guard_user_id',
          'local'        => 'assigned_to',
          'foreign'      => 'id',
          'foreignTable' => 'sf_guard_user',
          'onUpdate'     => '',
          'onDelete'     => 'SET NULL',
        )
      );
    }

    public function down()
    {
      $this->dropForeignKey('alternative', 'alternative_assigned_to_sf_guard_user_id');
      $this->removeColumn('alternative', 'assigned_to');
      $this->removeColumn('alternative', 'external_id');
      $this->removeColumn('alternative', 'notes');
      $this->removeColumn('alternative', 'work_progress');
      $this->removeColumn('alternative', 'due_date');
      $this->removeColumn('alternative', 'notify_date');
    }
}