<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddTableAlternativeType extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->createTable(
      'alternative_type',
      array(
        'id'         => array(
          'type'          => 'integer',
          'length'        => '8',
          'autoincrement' => '1',
          'primary'       => '1',
        ),
        'type_id'    => array(
          'type'    => 'bigint',
          'notnull' => '1',
          'length'  => '20',
        ),
        'name'       => array(
          'type'    => 'string',
          'notnull' => '1',
          'length'  => '64',
        ),
        'short_name' => array(
          'type'    => 'string',
          'notnull' => '1',
          'length'  => '64',
        ),
      ),
      array(
        'primary' => array(
          0 => 'id',
        ),
        'indexes' => array(
          'alternative_type_decision_type_idx' => array(
            'fields' => array(
              0 => 'type_id'
            ),
          ),
        ),
        'collate' => 'utf8_general_ci',
        'charset' => 'utf8',
      )
    );

    $this->addColumn('alternative', 'type_id', 'bigint', '20');
  }

  public function down()
  {
    $this->removeColumn('alternative', 'type_id');
    $this->dropTable('alternative_type');
  }
}