<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddGraphTypeMigration extends Doctrine_Migration_Base
{
    public function up()
    {
      $graphType = new GraphType();
      $graphType->name = 'xy';
      $graphType->save();

      $graphType = new GraphType();
      $graphType->name = 'bubble';
      $graphType->save();
    }

    public function down()
    {

    }
}