<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlternativeTypeAddRelation extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->createForeignKey('alternative', 'alternative_type_id_to_alternate_type_id',
      array(
        'name'         => 'alternative_type_id_to_alternate_type_id',
        'local'        => 'type_id',
        'foreign'      => 'id',
        'foreignTable' => 'alternative_type',
        'onUpdate'     => 'CASCADE',
        'onDelete'     => 'SET NULL',
      )
    );

    $this->createForeignKey('alternative_type', 'alternative_type_type_id_to_decision_type_id',
      array(
        'name'         => 'alternative_type_type_id_to_decision_type_id',
        'local'        => 'type_id',
        'foreign'      => 'id',
        'foreignTable' => 'decision_type',
        'onUpdate'     => 'CASCADE',
        'onDelete'     => 'CASCADE',
      )
    );
  }

  public function postUp(){
    $alternative_type = new AlternativeType();
    $alternative_type->type_id = 1;
    $alternative_type->name = 'Alternative';
    $alternative_type->short_name = 'ALT';
    $alternative_type->save();

    $alternative_type = new AlternativeType();
    $alternative_type->type_id = 2;
    $alternative_type->name = 'Feature';
    $alternative_type->short_name = 'FEA';
    $alternative_type->save();

    $alternative_type = new AlternativeType();
    $alternative_type->type_id = 3;
    $alternative_type->name = 'Project';
    $alternative_type->short_name = 'PRO';
    $alternative_type->save();

    $alternative_type = new AlternativeType();
    $alternative_type->type_id = 4;
    $alternative_type->name = 'Vendor';
    $alternative_type->short_name = 'VEN';
    $alternative_type->save();

    $alternative_type = new AlternativeType();
    $alternative_type->type_id = 5;
    $alternative_type->name = 'Candidate';
    $alternative_type->short_name = 'CAN';
    $alternative_type->save();

    Doctrine_Manager::getInstance()->connection()->execute("UPDATE alternative a LEFT JOIN decision d ON a.decision_id = d.id SET a.type_id = d.type_id");
  }


  public function down()
  {
    $this->dropForeignKey('alternative', 'alternative_type_id_to_alternate_type_id');
    $this->dropForeignKey('alternative_type', 'alternative_type_type_id_to_decision_type_id');
  }

  public function postDown(){
    Doctrine_Manager::getInstance()->connection()->execute("UPDATE alternative SET type_id = NULL;");
    Doctrine_Manager::getInstance()->connection()->execute("DELETE from `alternative_type` ");
  }
}