<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RandomizeItemId extends Doctrine_Migration_Base
{
    public function up()
    {
      $alternatives = Doctrine_Core::getTable('Alternative')
        ->createQuery('a')
        ->where('a.item_id is NULL')
        ->execute();

      foreach ($alternatives as $alternative){
        do{
          $id = mt_rand(1, 99999999);
        }while(count(Doctrine_Core::getTable('Alternative')->findByItemId($id)));

        $alternative->item_id = $id;
        $alternative->save();
      }
    }

    public function down()
    {

    }
}