<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DashboardMigrationSecond extends Doctrine_Migration_Base
{
  public function up()
  {
    $result = Doctrine_Manager::getInstance()->connection()->execute("SELECT id from `decision` WHERE id not in (SELECT d.id FROM `decision` d LEFT JOIN `role` r ON d.id = r.decision_id WHERE r.dashboard = 1) limit 500")->fetchAll();

    foreach ($result as $decision_row) {
      $decision = DecisionTable::getInstance()->find($decision_row['id']);
      $decision->createDashboard();
    }
  }

  public function down()
  {

  }
}
