<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddTableRoadmap extends Doctrine_Migration_Base
{
    public function up()
    {
      $this->createTable('roadmap', array(
          'id'         => array(
            'type'          => 'integer',
            'length'        => '20',
            'autoincrement' => '1',
            'primary'       => '1',
          ),
          'user_id'    => array(
            'type'    => 'integer',
            'notnull' => '1',
            'length'  => '20',
          ),
          'name'       => array(
            'type'    => 'string',
            'notnull' => '1',
            'length'  => '64',
          ),
          'description'=> array(
            'type'    => 'text'
          ),
          'link'       => array(
            'type'    => 'string',
            'length'  => '128',
          ),
          'folder_id'    => array(
            'type'    => 'integer',
            'length'  => '20',
          ),
          'active'      => array(
            'type' => 'boolean',
            'default' => '1'
          ),
          'status' => array(
            'type'    => 'enum',
            'values'  =>
              array(
                0 => 'Draft',
                1 => 'Reviewed',
                2 => 'Approved',
                3 => 'Under revision'
              ),
            'default' => 'Draft',
          ),
          'show_items'      => array(
            'type' => 'boolean',
            'default' => '1'
          ),
          'show_releases'      => array(
            'type' => 'boolean',
            'default' => '1'
          ),
          'show_dependencies'      => array(
            'type' => 'boolean',
            'default' => '1'
          ),
          'show_description'      => array(
            'type' => 'boolean',
            'default' => '1'
          ),
        ),
        array(
          'primary' =>
            array(
              0 => 'id',
            ),
          'collate' => 'utf8_general_ci',
          'charset' => 'utf8',
        )
      );

      $this->addColumn('folder', 'type', 'ENUM("project", "roadmap") DEFAULT "project"');

      $this->createTable('roadmap_decision', array(
        'id'         => array(
          'type'          => 'integer',
          'length'        => '20',
          'autoincrement' => '1',
          'primary'       => '1',
        ),
        'roadmap_id' => array(
          'type'          => 'integer',
          'length'        => '20',
          'notnull'       => '1',
        ),
        'decision_id' => array(
          'type'          => 'integer',
          'length'        => '20',
          'notnull'       => '1',
        ),
      ));
    }

    public function down()
    {
      $this->removeColumn('folder', 'type');
      $this->dropTable('roadmap');
      $this->dropTable('roadmap_decision');
    }
}