<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddFieldsToDecision extends Doctrine_Migration_Base
{
    public function up()
    {
      $this->addColumn('decision', 'start_date', 'datetime');
      $this->addColumn('decision', 'end_date', 'datetime');
      $this->addColumn('decision', 'color', 'varchar', 8);
    }

    public function down()
    {
      $this->removeColumn('decision', 'start_date');
      $this->removeColumn('decision', 'end_date');
      $this->removeColumn('decision', 'color');
    }
}