<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddTableAlternativeRelation extends Doctrine_Migration_Base
{
    public function up()
    {
      $this->createTable('alternative_relation', array(
        'id'         => array(
          'type'          => 'integer',
          'length'        => '20',
          'autoincrement' => '1',
          'primary'       => '1',
        ),
        'from_id'    => array(
          'type'    => 'integer',
          'notnull' => '1',
          'length'  => '20',
        ),
        'to_id'    => array(
          'type'    => 'integer',
          'notnull' => '1',
          'length'  => '20',
        ),
        'created_at' => array(
            'notnull' => '1',
            'type'    => 'timestamp',
            'length'  => '25',
        ),
        'created_by' => array(
          'notnull' => '1',
          'type'    => 'varchar',
          'length'  => '255',
        ),
      ),
      array(
        'primary' =>
          array(
            0 => 'id',
          ),
        'collate' => 'utf8_general_ci',
        'charset' => 'utf8',
      ));

      $this->createForeignKey('alternative_relation', 'alternative_relation_from_id_to_alternative_id',
        array(
          'name'         => 'alternative_relation_from_id_to_alternative_id',
          'local'        => 'from_id',
          'foreign'      => 'id',
          'foreignTable' => 'alternative',
          'onUpdate'     => 'CASCADE',
          'onDelete'     => 'CASCADE',
        )
      );

      $this->createForeignKey('alternative_relation', 'alternative_relation_to_id_to_alternative_id',
        array(
          'name'         => 'alternative_relation_to_id_to_alternative_id',
          'local'        => 'to_id',
          'foreign'      => 'id',
          'foreignTable' => 'alternative',
          'onUpdate'     => 'CASCADE',
          'onDelete'     => 'CASCADE',
        )
      );
    }

    public function down()
    {
      $this->dropForeignKey('alternative_relation', 'alternative_relation_to_id_to_alternative_id');
      $this->dropForeignKey('alternative_relation', 'alternative_relation_from_id_to_alternative_id');
      $this->dropTable('alternative_relation');
    }
}