<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddStatusToDecision extends Doctrine_Migration_Base
{
    public function up()
    {
      $this->addColumn('decision', 'status', 'ENUM("Planned", "In Progress", "Done") DEFAULT "Planned"');
    }

    public function down()
    {
      $this->removeColumn('decision', 'status');
    }
}