<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddTokenToRoadmap extends Doctrine_Migration_Base
{
    public function up()
    {
      $this->addColumn('roadmap', 'token', 'varchar', '6', array(
        'notnull' => true
      ));
      $this->removeColumn('roadmap', 'link');
    }

    public function down()
    {
      $this->removeColumn('roadmap', 'token');
    }
}