<?php

/**
 * PluginTeamMemberTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTeamMemberTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTeamMemberTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTeamMember');
    }
}